### ISSUE TITLE
quick_latex

### ISSUE THREAD

**Issue by nikolassch** [hughjonesd/huxtable#101]
As already mentioned in this thread (https://github.com/hughjonesd/huxtable/issues/81), it would be great to be able to export a tex file which then can be used in an external latex editor (in particular overleaf). I tried
my_table %>% to_latex(tabular_only = F) %>% write(file = "output.tex")  and included the packages from the report_latex_dependencies() but the document won't compile.

In the end, it is not realistic to write larger projects in markdown so being able to export it properly would be very important!

**Comment by hughjonesd** [comment]
Could you give me a more precise problem than “the document won’t compile“? An example of the document, and the error messages from TeX, would be great.

**Comment by hughjonesd** [comment]
In any case, I think `quick_latex()` is probably a good idea. Implemented in master on github. Please try out with `remotes::install_github("hughjonesd/huxtable")` if you can.
