### ISSUE TITLE
Chinese colnames

### ISSUE THREAD

**Issue by rhohz** [hughjonesd/huxtable#106]
Hi

When I use Chinese header, warnings occur. For example:

`tribble_hux(
   ~ 中文,  ~ 英文,
      1,           2,
      3,           4,
   add_colnames = TRUE)`

How to handle this problem?

Thanks

**Comment by hughjonesd** [comment]
Thanks. Yes, this is a tricky bug in screen.R ... It's going to be hard to fix because the code assumes that each character fits in a single screen line. Will think.

**Comment by hughjonesd** [comment]
Here's an example showing the issue more clearly:

```
tribble_hux( ~ 中文英文英文英文, ~ 英文, 1, 2, 3, 4, add_colnames = TRUE)
##   中文英文英文英文        中文英     英文    
##                  1           2  
##                  3           4  
## 
## Column names: 中文英文英文英文, 英文
```

**Comment by hughjonesd** [comment]
Please tell me if this works for you in github master!
