### ISSUE TITLE
"Indicate" a set of (e.g. Dummy or factor) coefficients

### ISSUE THREAD

**Issue by daaronr** [hughjonesd/huxtable#108]
```
mtcars$hpfac <- as.factor(mtcars$hp)

big <-lm(mpg ~ wt+hpfac, data = mtcars) 

small <-lm(mpg ~ wt, data = mtcars) 

huxreg(big, small)
```

But I don't want 15 or so huxtable rows for hpfac for the 'big' model (first) column. I just want a single row that says "hpfac (yes)" ... and maybe a test for joint significant or some other stat. 

Stata's eststo/estout can do it with the 'indicate' thing. Can I do it in Huxtable? I'd love to be able to.

**Comment by hughjonesd** [comment]
You can do it manually. But  dealing with the many ways to represent
regression results is out of scope for huxtable, I think.
-- 
Sent from Gmail Mobile
