### ISSUE TITLE
add_rows throws names error when adding multiple rows to huxreg

### ISSUE THREAD

**Issue by pbaylis** [hughjonesd/huxtable#112]
**Describe the bug**
`add_rows` gives an error when adding multiple rows to the output of `huxreg`.

**Minimal Reproducible Example**
```
library(huxtable)

hux_out <- huxreg(lm(mpg ~ cyl, mtcars)) 
hux_out_added <- add_rows(hux_out, rbind(c("row1", "30"), 
                                         c("row1", "30")))
hux_out_added
```
Throws the following error: `Error in names(attr(ht, a)) <- dimnames(ht)[[1]] : 
  'names' attribute [12] must be the same length as the vector [11]`

**Expected behavior**
`huxreg` output plus the two additional rows given in `add_rows`.

**System details**
OS X 10.14.5
huxtable version: 4.5.0
R version: 3.5.1
RStudio version: 1.2.1335

**Comment by hughjonesd** [comment]
Thanks for the great bug report.

Simpler version:
```
ht <- as_hux(matrix(1, 1, 1))
prob <- rbind(ht, rbind(1,1))
row_height(prob) # should be 3-vector, is 2-vector
```
