### ISSUE TITLE
Add as_hux function for etables (expss package) 

### ISSUE THREAD

**Issue by sjewo** [hughjonesd/huxtable#117]
**Describe what is missing**
The `expss` package by @gdemin makes it easy to create complex tables, but has only limited features to export those tables to word or latex. A conversions method from a etable (expss) to a huxtable would help to make publication ready tables from within R.

**Describe your proposed solution**
I made a working, but not complete example for a conversion function: 6079014b0

**Target audience**
Users of expss and huxtable

**Additional context**
I'm willing to finish the conversion function and to make a pull request if you're interest to add this feature.

**Comment by hughjonesd** [comment]
Looks interesting. My feeling is the conversion function would belong in
the expss package.

>

**Comment by sjewo** [comment]
Thanks for your feedback! 
@gdemin is willing to include the conversion function in `expss`.
