### ISSUE TITLE
how to add math formulas?

### ISSUE THREAD

**Issue by randomgambit** [hughjonesd/huxtable#118]
Hi!

Thanks this package is amazing!! I was wondering, is it possible to render a math formula in the console? Does Huxtable handle mathjax for instance?

**Comment by hughjonesd** [comment]
You seem to have missed the notice I put on both forms of new issue template. Let me repeat it here for you:

**PLEASE DON'T USE GITHUB ISSUES FOR HELP REQUESTS.**

**Comment by randomgambit** [comment]
sorry i missed it. no need to be rude.

**Comment by hughjonesd** [comment]
No dude, you're the rude guy. You're wasting my time and spamming my github issues. I explicitly asked you not to, right there in capital letters, when you filled in the form. Please stay away - don't post, don't ask for help, use different software. You are repaying me for the free software I offered you by wasting my time. I do not want to hear from you again.
