### ISSUE TITLE
latex support for html output

### ISSUE THREAD

**Issue by kurt1984** [hughjonesd/huxtable#119]
Hi, I tried the code below, but the output not aligned. 

library(huxtable)
ht <- huxtable(
Exponent = 2:4,
Example = paste0("$$x^", 2:4, "$$"),
add_colnames = TRUE
)

ht <- set_all_padding(ht, 1:3, 1:2, "0px")
escape_contents(ht)[,2] <- FALSE
ht
<img width="181" alt="Screen Shot 2019-11-03 at 2 01 33 PM" src="https://user-images.githubusercontent.com/3388284/68091212-76722700-fe42-11e9-8b6d-1d450e399744.png">

**Comment by hughjonesd** [comment]
In LaTeX? HTML? on-screen?

**Comment by kurt1984** [comment]
Thanks so much for speedy response!

I knit to html

**Comment by hughjonesd** [comment]
More information needed. If I do quick_html, I just see the dollar signs -
not surprisingly because these are LaTeX escapes. You must be doing
something to convert the TeX to HTML - maybe using a rmarkdown document?
Please provide a self-contained example that I can reproduce.

**Comment by kurt1984** [comment]
Thanks! Yes, it is a rmd as below.  BTW, what is html way to include latex math?

---
title: "Untitled"
date: "11/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
 
```{r}
library(huxtable)
ht <- huxtable(
Exponent = 2:4,
Example = paste0("$$x^", 2:4, "$$"),
add_colnames = TRUE
)

ht <- set_all_padding(ht, 1:3, 1:2, "0px")
escape_contents(ht)[,2] <- FALSE
ht
```

**Comment by hughjonesd** [comment]
OK, I see the issue. I'd say this is an unfortunate result of how mathjax interacts with the default style for huxtable. As a workaround, add:

```
ht <- set_valign(ht, "middle")
```

which seems to give a nicer result.
