### ISSUE TITLE
Support for tidied objects with column `y.level`

### ISSUE THREAD

**Issue by chrishanretty** [hughjonesd/huxtable#124]
# What is missing

Multinomial models have category-specific coefficients. Broom tidiers deal with category specific coefficients by returning a data frame with additional column `y.level`. huxreg currently ignores all coefficients other than the coefficients for the first value of `y.level`.

# What would be good

Some way of allowing users to specify the alternative for which they wish to show coefficients.

#  A possible solution

Adding an additional argument ylevel. It would be possible to show all coefficients by passing the same model multiple times with different values of ylevel. For example:

huxreg(mod, mod, mod, ylevel = c("Lab", "Dem", "Other"))

**Comment by hughjonesd** [comment]
My feeling is that this would be valuable, but it strays too far from huxtable's core mission of printing out tables - huxreg is really just a quick hack, though it is useful to many. You might consider the github version of texreg, which has a huxtablereg() output function and which also (IIRC) deals with multinomial models.

**Comment by hughjonesd** [comment]
If you try the latest from github, the example from the new `tidy_replace()` function should have what you need.

**Comment by hughjonesd** [comment]
Closing. See the huxreg vignette (github version).
