### ISSUE TITLE
huxtable fails to autonumber tables in bookdown documents

### ISSUE THREAD

**Issue by dmenne** [hughjonesd/huxtable#125]
I have posted a comment on 

https://community.rstudio.com/t/table-numbering-in-bookdown-why-can-only-kable-do-it-portably-huxtable-pander-flextable-fail/54313

showing how `knitr::kable` nicely autonumbers tables in bookdown documents for HTML and Word, while `huxtable and pander` fail for both and `flextable` only works with HTML. I might have used some examples wrongly, so please feel free to correct me.

**Comment by hughjonesd** [comment]
Think this is an issue with flextable. See my comment at the linked web page.

**Comment by hughjonesd** [comment]
Depends on davidgohel/flextable#193

**Comment by dmenne** [comment]
Flextable now support autonumbering, so I assumed that huxtable would automatically follow. I have not been successful, though. See https://gist.github.com/dmenne/f8eb291c9e71a5de44764d442e8bdefd
for a commented demo.

**Comment by hughjonesd** [comment]
Here's how to do it in HTML. Note that huxtable doesn't currently autoset the label from the knitr chunk - maybe it should. I've also included code that lets you run huxtable and flextable in the same document (just disambiguate the set_caption call).
````


```{r flexiris, echo=FALSE}
suppressPackageStartupMessages(library(flextable))
ft =  flextable( head( iris ) )
ft = flextable::set_caption(ft, "Iris with flextable")
ft
```

### `huxtable`

```
{r huxiris, echo=FALSE}
suppressPackageStartupMessages(library(huxtable))
hx =  hux( head( iris ) ) 
hx = add_colnames(hx)
hx = huxtable::set_caption(hx, "Iris with huxtable")
hx = huxtable::set_label(hx, "tab:huxiris")
hx
```
````

If I render this using `bookdown::html_document2`, the huxtable link at the bottom of the gist works.

I've also tried the following word document:

````
---
title: "Table numbering in Word"
output: 
  bookdown::word_document2:
    toc: true
    keep_md: true
---

```{r,  echo=FALSE}
library(knitr)
opts_chunk$set(warning = FALSE, echo = FALSE)
mt <- head(mtcars)
```


### flextable

```{r tab:mtflex}
f <- flextable::flextable(head(mtcars))
f <- flextable::set_caption(f, "Flextable caption")
f
```

### huxtable

```{r tab:mthux}

options('huxtable.bookdown'=TRUE) # Should be automatic, just to be sure
h = huxtable::huxtable(mt)
huxtable::caption(h) = "No special details in caption"
h

```

````

For me, this now gives identical results between flextable and huxtable (though both of them print some not very nice text, so I guess this is still not completely what users want).

**Comment by hughjonesd** [comment]
NB: this was with current github `flextable` and `officer`.

**Comment by dmenne** [comment]
Gist was updated

**Comment by hughjonesd** [comment]
OK. It sounds like I can close this bug - or are there remaining problems?

**Comment by dmenne** [comment]
>> Note that huxtable doesn't currently autoset the label from the knitr chunk - maybe it should. 

This would be nice. A feature that leads to consistent behaviour so that any `kable` can be replaced.

**Comment by hughjonesd** [comment]
Interesting. Can you do me a favour and tell me what the other alternative packages do in this area? You are the current expert on this topic....

**Comment by dmenne** [comment]
If by "what" you mean "what code they use": It's long ago that I have looked into the details of chunk parameters, even if it was me who encouraged yihui to allow expressions in the chunk header.  

Strangely, it works with flextable, so I thought that this would carry over without explicit code. So something like: if there is a chunk label use it as default for setlabel.

**Comment by hughjonesd** [comment]
I don't mind about the implementation - I just want to know if in general, they label tables from chunk headers. If that is an established convention, I'd consider following it. OTOH I can see the downside - for example, what if a single chunk produces multiple tables?

**Comment by dmenne** [comment]
It's a price to be paid for convencience. I checked with kable, if you do this, you get two numbered tables 1.1 anyway, so autonumber anyway fails. Same happens with huxtable. For figures, yihui has put a lot of code to handle this, which I appreciate. But I would not mind to have a "one-chunk-one-Table" philosopy.

**Comment by januz** [comment]
I also think that it is a good idea to establish a "one chunk-one table" standard!

I don't know whether this is directly related, but I came to see this issue because I couldn't get the example from this [Stackoverflow post](https://stackoverflow.com/a/53337093) to work with my custom R Markdown template that is based on `bookdown::html_document2`, while `kable` tables worked as expected.

Playing a bit around with the newest Github versions of `flextable` and `huxtable`, I found that using

```
hux(a = 1:5, b = 1:5) %>% 
  set_caption("(#tab:mthux)My table")
``` 

now works with my template, while 

```
hux(a = 1:5, b = 1:5) %>% 
  set_caption("My table") %>% 
  set_label("mthux")
```

or

```{r mthux}
hux(a = 1:5, b = 1:5) %>% 
  set_caption("My table")
```

do not. When replacing my custom template with `bookdown::html_document2`, all three ways work.

**Comment by hughjonesd** [comment]
Set `options(huxtable.bookdown = TRUE)`. The package tries to guess whether we are in bookdown, and will probably fail for your custom template. (You can see how by looking at the source code for `huxtable:::in_bookdown`, but I wouldn't recommend relying on that behaviour!)

**Comment by hughjonesd** [comment]
Think this is now fixed. Reopen if not.

**Comment by hughjonesd** [comment]
Hmm, works for me in HTML but not in Word. I think this is related to https://github.com/rstudio/bookdown/issues/746.

A workaround is:

```r
set_caption("(\\#tab:testhuxtab) This is table to test hux crossref in word")
```

Unfortunately this makes the ugly label visible in the caption, but this is the only way I know of to make flextable produce captions. It may be that you can do something by explicitly converting with `as_flextable` and using `flextable::set_caption`, which has an `autonum` option.

**Comment by mingsu** [comment]
@hughjonesd Thanks.

This is not working for me.

```
set_caption("(\\#tab:testhuxtab) This is table to test hux crossref in word")
```

By trying many ways, I found this works.

````
---
title: "test hux"
output:
  bookdown::word_document2:
    toc: no
  bookdown::html_document2:
    toc: no
---


See Table \@ref(tab:testhuxtab)

```{r testhuxtab, tab.cap = "This is table to test hux crossref in word"}
require(magrittr)
require(huxtable)
options(huxtable.bookdown = T)

huxtable(column1 = 1:5,
         column2 = letters[1:5]
         ) %>%
huxtable::as_flextable()
```

````
