### ISSUE TITLE
Missing fontspec package dependency with latex_use_fontspec option

### ISSUE THREAD

**Issue by chris2b5** [hughjonesd/huxtable#126]
**Describe the bug**
Having set `options("huxtable.latex_use_fontspec"=TRUE)`, the `fontspec` package should be included in the LaTeX output and `report_latex_dependencies()`, but isn't. As a result, compiling the LaTeX output complains that `\fontspec` is an undefined control sequence, and fails.

**Minimal Reproducible Example**
```R
library(magrittr) # for %>%
library(huxtable)
options("huxtable.latex_use_fontspec"=TRUE)
jams %>% as_hux() %>% set_font("Arial") %>% quick_pdf()
```
**Expected behavior**
A `\usepackage{fontspec}` should be emitted in the LaTeX output so that the PDF in the reprex builds properly. Have verified that adding this after all other `\usepackage` lines works OK for the reprex.

**System details**
```
> packageVersion("huxtable")
[1] ‘4.7.1’

# R --version
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

RStudio Version 1.2.5033
```

**Comment by hughjonesd** [comment]
Do you have tinytex installed? If not, then see ?huxtable-options :

> 
> This requires the the xetex or xelatex
>           engine, which can be set using an .rmd header option. Note
>           that ‘quick_pdf()’ may use pdflatex.

However, if you try the latest commit on master, it may work for you - please give it a shot, and tell me what happens. To do this, run:

```
install.packages("remotes")
remotes::install_github("hughjonesd/huxtable")
```

**Comment by chris2b5** [comment]
Thanks very much for coming back on this. I use MiKTeX and I see from the .log that `quick_pdf()` is using xelatex / xetex.

No change in the behaviour with the latest master 71988968942a17bc5ce2bf4530aaa728130c9c8d .
(have checked that latest version 4.7.1.9000 is being used).

Doing `quick_latex()` instead shows that `\usepackage{fontspec}` is still missing in the latex output, and building the latex output manually on the command line with pdflatex, xelatex etc all fails in the same way as described above. Adding `\usepackage{fontspec}` after all other `\usepackage` directives at the top of the tex output file fixes it for me.

I took a look at the code. For markdown / knitr the fontspec package dependency is handled here: https://github.com/hughjonesd/huxtable/blob/71988968942a17bc5ce2bf4530aaa728130c9c8d/R/knitr.R#L48 but as I am working in a standalone R script using the `quick_` functions this doesn't help. Maybe a similar fix in `do_write_latex_file` here https://github.com/hughjonesd/huxtable/blob/71988968942a17bc5ce2bf4530aaa728130c9c8d/R/quick-functions.R#L252 would work, or else move the fix into `report_latex_dependencies` here https://github.com/hughjonesd/huxtable/blob/71988968942a17bc5ce2bf4530aaa728130c9c8d/R/latex-dependencies.R#L43 even?

Hope this helps. Happy to share logs / etc. if useful.

**Comment by hughjonesd** [comment]
Try now.
