### ISSUE TITLE
set width of table caption independent of table width in HTML output

### ISSUE THREAD

**Issue by januz** [hughjonesd/huxtable#128]
**Describe what is missing**

I like that `huxtable` determines column widths automatically and displays tables in a compact manner. I don't like that the caption width is dependent on the table width. This makes for a relatively cluttered document view in my opinion, with tables of different width (but approximately the same caption length) having vastly different captions (some spanning over several lines). The desired solution would be more similar to how figures and their captions are set.

**Describe your proposed solution**

Ideally one would be able to set the caption in an independent container with an added function like `set_caption_width()`.

**Target audience**

People preparing more formal documents with R Markdown (e.g., academic journal submissions)

**Comment by hughjonesd** [comment]
I can be convinced, but am wary of adding complexity. Can you show me an example where the current setup looks bad?

**Comment by januz** [comment]
Thanks for the consideration! Here's an example

````
---
title: "Caption test"
output:
  bookdown::html_document2
---

```{r setup, include=FALSE}
library(dplyr)
library(huxtable)
knitr::opts_chunk$set(echo = FALSE)
options(
  huxtable.bookdown = TRUE,
  huxtable.add_colnames = TRUE
)
long_caption <- 'This is a long caption. This is a long caption. This is a long caption. This is a long caption. This is a long caption. This is a long caption. This is a long caption. This is a long caption. This is a long caption.'
```

# Left aligned layout

This is the layout I personally would like to use. But I feel like `huxtable`'s caption looks crammed:

```{r huxtable-left}
head(mtcars[, 1:2], 10) %>% 
  tibble::rownames_to_column() %>% 
  as_huxtable() %>%
  theme_article() %>% 
  huxtable::set_position("left") %>% 
  set_caption(long_caption)
```

I would prefer it to span the whole width like this one by `kable` (but without having the table also span the whole width):

```{r kable}
knitr::kable(
  head(mtcars[, 1:2], 10),
  caption = long_caption
)
```

More like in this figure:

```{r fig-left, fig.cap = long_caption, echo=FALSE}
plot(runif(10))
```

# Centered layout

When using a centered layout I feel the same. This seems too crammed:

```{r huxtable-center}
head(mtcars[, 1:2], 10) %>% 
  tibble::rownames_to_column() %>% 
  as_huxtable() %>%
  theme_article() %>% 
  set_caption(long_caption)
```

This looks better:

```{r fig-center, fig.align = "center", fig.cap = long_caption, echo=FALSE}
plot(runif(10))
```
````

**Comment by hughjonesd** [comment]
Note  to self: 

* in LaTeX, the caption package lets you specify `width` in `\captionsetup`. 

* in HTML, you can style the caption element with `width`.

**Comment by hughjonesd** [comment]
The fact that captions were sometimes too long originally motivated me to use threeparttable. That leads to this bug. 

One possibility would be to have `caption_width` which could be a length; if NA, it would follow the table as now.

**Comment by hughjonesd** [comment]
Hi januz,
Could you test the github version with

```
devtools::install_github("hughjonesd/huxtable")
```

It has a new `caption_width()` property which should be what you want. Currently working in HTML and PDF

**Comment by januz** [comment]
Hey @hughjonesd Thanks, works great!

One thing I noticed though is that in the new version the length of the footnote seems to determine the width of the table:

![image](https://user-images.githubusercontent.com/1440498/81475962-1fb82200-91c4-11ea-83ab-e327d23fbfb6.png)

I expected the old behavior, i.e., that the footnote width would be determined by the table width and thus would be broken over several lines.

**Comment by hughjonesd** [comment]
Is this with the table width explicitly set? It no longer defaults to
0.5....
David

**Comment by januz** [comment]
Yes, sorry, I didn't set the table with explicitly. I was confused, because for other tables without footnotes the table width was set automatically based on the columns. But this behavior makes more sense. Thank you so much for the implementation!!
