### ISSUE TITLE
Use commonmark to format strings as markdown

### ISSUE THREAD

**Issue by mingsu** [hughjonesd/huxtable#130]
Great package!

To specify font style for some characters is very useful, such as:

- add a footnote label (superscript style)
- italic or bold font for some words within a cell

Currently, the `set_italic`, `set_bold` are at cell level, is it possible or worth to do it?

**Comment by hughjonesd** [comment]
The best thing is to use text like e.g. "the next word is in <i>italic</i>" and then set `escape_contents` to `FALSE`. That requires that you know the output format, of course.

**Comment by mingsu** [comment]
> The best thing is to use text like e.g. "the next word is in italic" and then set `escape_contents` to `FALSE`. That requires that you know the output format, of course.

Thanks for  your quick reply.

You are right, and this is a possible solution for now.  I was thinking it would be a great feature if supporting it naturally. In many cases, the output format can be multiple. Like my case for now, I can write special functions to fit the `HTML` and `LATEX` output format, but I don't know how to make it work for `DOCX` and other MS office format.

**Comment by hughjonesd** [comment]
Simplest option would probably be to support markdown and then write translators - or reuse existing ones. Cf. gt.

**Comment by hughjonesd** [comment]
commonmark could be a friend here. It has translators for html, latex and text.

**Comment by mingsu** [comment]
Thanks, I have looked into `commonmark`, but it seems beyond my knowledge to imbed into `huxtable` or in R functions.

**Comment by hughjonesd** [comment]
I am writing notes to myself re implementation. If you want to do this, you could do something like:

```
text <- "Some **markdown** text"
formatted_text <- switch(
    huxtable::guess_knitr_output_format(),
   "html"  = commonmark::markdown_html(text),
    "latex" = commonmark::markdown_latex(text)
)
huxtable(text = formatted_text)
```

**Comment by januz** [comment]
It would be amazing if you could implement markdown support (plus translators to different output formats). This seems to work in `kable` already. In general, `kable`'s handling of different output formats is more consistent, also with regard to math (`huxtable` only seems to work with `$$...$$` when output is HTML and `$...$` when output is LaTeX), see

````
---
title: "kable vs. huxtable"
output: pdf_document # html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(magrittr)

check_output_format <- function(output_format) {
  output_format %in% knitr::opts_knit$get("rmarkdown.pandoc.to")
}

table_text <- tibble::tribble(
  ~syntax, ~sub, ~super, ~bold, ~italic,
  "HTML", "text<sub>subscript</sub>","text<sup>superscript</sup>", "<b>text</b>", "<i>text</i>",
  "LaTeX", "text\\textsubscript{subscript}", "text\\textsuperscript{superscript}", "\\textbf{text}", "\\textit{text}",
  "Markdown", "text~subscript~", "text^superscript^", "**text**", "*text*"
)

table_math <- tibble::tribble(
  ~syntax, ~math,
  "inline", "$ln\\left(\\frac{\\pi_i}{1-\\pi_i}\\right)$",
  "inline with text", "The coefficient $\\beta_2$",
  "equation", "$$ln\\left(\\frac{\\pi_i}{1-\\pi_i}\\right)$$"
)
```

## kable

```{r kable}
table_text %>% 
  knitr::kable()

table_math %>% 
  knitr::kable()
```

## huxtable
```{r huxtable}

if (check_output_format("html")) {
  table_text %>%
    huxtable::as_hux() %>%
    huxtable::theme_article() %>% 
    huxtable::set_escape_contents(FALSE)
} else {
  table_text %>%
    dplyr::slice(-3) %>%  # huxtable throws error when using ^
    huxtable::as_hux() %>%
    huxtable::theme_article() %>% 
    huxtable::set_escape_contents(FALSE)
}
  
if (check_output_format("html")) {
  table_math %>%
    huxtable::as_hux() %>% 
    huxtable::theme_article() %>% 
    huxtable::set_escape_contents(FALSE)
} else {
  table_math %>%
    dplyr::slice(-3) %>%  # huxtable throws error when using $$
    huxtable::as_hux() %>% 
    huxtable::theme_article() %>% 
    huxtable::set_escape_contents(FALSE)
}
```
````

**Comment by hughjonesd** [comment]
I'm persuaded this is a good idea. It'll happen either in 5.0.0 or in the next release. Incidentally, if you'd like to try out 5.0.0, most of that code has now been merged into master.

**Comment by hughjonesd** [comment]
Fixed in 901c0.

**Comment by mingsu** [comment]
Thanks for your effort to make this happen.
I agree with @januz, that would be great to support more markdown syntax.

**Comment by hughjonesd** [comment]
It should do most things in LaTeX/HTML. Screen output will be limited by definition. It won't support built-in tables or other extensions (what kind of sicko would do that?). But it's limited by the commonmark implementation. If you have specific bugs, file them.
