### ISSUE TITLE
Allow setting padding with wrap

### ISSUE THREAD

**Issue by potterzot** [hughjonesd/huxtable#133]
Before using this form, please read `?"huxtable-FAQ"`. In particular:

**Description**

When wrapping text in a cell, sometimes we still want to change cell padding (especially to indent sub-categories). We can do this now by creating a first column that is blank and merging all non-indented cells across the two columns, but it would be easier to be able to use padding and wrap together, e.g. something like

```{r}
data(mtcars)
d <- cbind(row.names(mtcars), mtcars)[1:5,1:5]
names(d)[1] <- "car"

# Would allow wrapped text within a padded column
h1 <- hux(d, add_colnames = TRUE) %>%
  set_wrap(, 1, TRUE) %>%
  set_left_padding(2:6, , 8)
```

**Target audience**
Anyone looking to table sub-categories of items where the total is not indented but the sub categories are.

**Additional Context**

It looks like this happens on [line 277 of latex.R](https://github.com/hughjonesd/huxtable/blob/d62e785b2a19962bd38dc5134083e4abf0ade526/R/latex.R#L277), where if wrap is set it does not set the padding.

Thanks! Wonderful package.

**Comment by hughjonesd** [comment]
Hi Nick,
Thanks for the suggestion. Could you try the latest github with 

```
devtools::install_github("hughjonesd/huxtable")
```

LaTeX output is changing a lot and this may fix your issue.

**Comment by potterzot** [comment]
Thanks for such a quick response! Installing from github does fix the padding issue, but `set_wrap()` no longer had an effect without specifying table width directly. For example:

```{r}
hux(d) %>%
  set_col_width(1, 0.3) %>%
  set_wrap(, 1, TRUE) %>% # does not wrap text in the first column, even with explicit width set
  set_left_padding(4:7, 1, 12) %>% # adds padding to rows 4-7 in the first column.
  add_footnote("Some $\\emph{italicized}$ text here...") %>%
  set_wrap(nrow(d)+1, , TRUE) %>%
  set_escape_contents(FALSE)
```
Provides padding but no wrapping of text. Instead the table extends off the page. However, adding an explicit table width definition like `set_width(0.8)` does enforce wrapping. In the end, this achieves the desired effect using the current development version:

```{r}
hux(d) %>%
  set_width(0.8) %>%
  set_col_width(1, 0.3) %>%
  set_left_padding(4:7, 1, 12) %>% # adds padding to rows 4-7 in the first column.
  add_footnote("Some $\\emph{italicized}$ text here...") %>%
  set_escape_contents(FALSE)
```

Thanks!

**Comment by hughjonesd** [comment]
That indeed sounds right and is by design. The theory is that unless you decide on an explicit width, wrapping is pointless. See the NEWS file.
