### ISSUE TITLE
Make markdown work for rtf, flextable

### ISSUE THREAD

**Issue by hughjonesd** [hughjonesd/huxtable#140]
RTF is hard since it is a DIY job. Perhaps the same is true of flextable?

**Comment by hughjonesd** [comment]
See https://davidgohel.github.io/officer/reference/fpar.html for how to add italic et al. within a paragraph. Or possibly https://davidgohel.github.io/flextable/articles/display.html which is within `flextable`. Maybe @davidgohel might think of markdown as an input format?

**Comment by hughjonesd** [comment]
`commonmark::markdown_xml` is useful, as it returns a correct parse tree. This might even be appropriate for `markdown_screen`.

**Comment by davidgohel** [comment]
Hi. Sorry, I never thought about markdown as input format for tables. I like data.frame (or matrix) as the main input of flextable

**Comment by hughjonesd** [comment]
@davidgohel It might make sense as an easy way for people to enter structured text. I'm not thinking of markdown for representing table structure, but for paragraphs of cell content. Would you be open to a pull request?

**Comment by davidgohel** [comment]
OK

I think package ftExtra is already implementing that: https://cran.r-project.org/package=ftExtra

Does it cover all your needs?

**Comment by hughjonesd** [comment]
Thanks. Yes, that could definitely be useful.

**Comment by hughjonesd** [comment]
See https://github.com/atusy/ftExtra/issues/10 for how to use markdown in flextable.

**Comment by atusy** [comment]
After closing #10, I decided to chose a different way.
Please take a look at https://github.com/atusy/ftExtra/issues/10#issuecomment-661056802
