### ISSUE TITLE
Adding footnote changes bottom border thickness

### ISSUE THREAD

**Issue by januz** [hughjonesd/huxtable#142]
**Describe the bug**

Sorry for another issue, but with the latest Github version adding a footnote leads to the bottom border being displayed thinner. 

**Minimal Reproducible Example**

```
library(huxtable)
data(jams)
jams_df <- data.frame(jams)

jams_df %>%
  as_huxtable(add_colnames = FALSE) %>%
  set_outer_borders(2) %>%
  add_footnote("A footnote") %>% 
  quick_html(file = "test.html")
```

**Expected behavior**

Border thickness should be the same as when not using a footnote.

**System details**

huxtable: 4.7.1.9000
R: 3.6.0

**Comment by hughjonesd** [comment]
From ?add_footnote:

```
Usage
add_footnote(ht, text, border = 0.8, ...)
```
...

```
border Width of the footnote's top border. Set to 0 for no border, or
NULL to leave the border unchanged.
```

**Comment by januz** [comment]
Argh, sorry! I was under the impression that this only had changed after updating to the latest Github version.
