### ISSUE TITLE
numeric caption_width meaning varies between HTML, TeX

### ISSUE THREAD

**Issue by hughjonesd** [hughjonesd/huxtable#143]
**Describe the bug**

Captions always end up on the left.

**Minimal Reproducible Example**

```
jams %>% 
      set_caption_pos("topright") %>% 
      set_caption_width(0.25) %>% 
      set_caption("A table of jams") %>% 
      quick_html()
```

**Expected behavior**

Both width and position should be respected.

**System details**

Version 4.7.1.9000

**Comment by hughjonesd** [comment]
The underlying issue is that CSS `width` of a caption refers to the width of the containing element, i.e. the table. At the moment we accept this and say that numeric caption_width varies between formats. The ideal would probably be to have caption_width always be of text/containing element width, but this is hard in HTML.

**Comment by januz** [comment]
I was just about to ask about this, i.e., is it possible to set caption width based on text width in HTML. This would best complement best how figure captions are set.

**Comment by hughjonesd** [comment]
If you can figure out a way to do it in HTML, I can try to implement it. (I got stuck. The problem is that the containing block of a `caption` is the table, not the text. Would the `vw` CSS length be useful?) Or if you wanted to make a pull request...

**Comment by januz** [comment]
Hm, I see. I looked into it briefly, but couldn't come up with an obvious way how to implement it.

One thing I thought of: Maybe one could set the table width to always match the viewport width. The chosen actual size and location of the table would than have to be implemented using "invisible" column(s) that absorb the remaining width, e.g.,

- when the table is left aligned, an invisible column on the right
- when the table is right aligned, an invisible column on the left
- when the table is centered, invisible columns on the left and right that each absorb half of the remaining width

As table width and viewport width would be the same, `caption_width` could be set based on percentage of the viewport width.

I don't know whether this makes sense and/or is easy to implement...

**Comment by hughjonesd** [comment]
Too crazy, I think, just for the purpose of getting a wide caption. 

After experimenting, I think this bug is invalid. Trying it out, the caption width seems to refer to the containing element. There are problems with text-align, but that is a separate issue.
