### ISSUE TITLE
bug in dev version printing hux tables

### ISSUE THREAD

**Issue by ddsjoberg** [hughjonesd/huxtable#153]
Hello @hughjonesd !

I was doing some testing on the dev version of huxtable against the recent gtsummary release. I think the update recently made moving options set in `.onLoad` to `.onAttach` may have introduced a bug when printing a huxtable when the package is not attached. (I do , however, agree with you that removing the option from onLoad was the correct thing to do.)

Below is a small R markdown example using huxtable without first attaching the package.  The printed table does not include the nice formatting from huxtable.

````r
---
title: "huxtable test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
huxtable::hux(head(mtcars))
```
````

![image](https://user-images.githubusercontent.com/26774684/83667595-a7fbce00-a59c-11ea-99f6-c259f446b19b.png)

**Comment by hughjonesd** [comment]
Oof, nice catch.

**Comment by ddsjoberg** [comment]
@hughjonesd doesn't moving that block of code back to `.onLoad` make huxtable the default print method for data frames in R markdown?  

In the R markdown example below, a gtsummary user (who may know nothing of huxtable) will now have all data frames printed with huxtable.  This can be very confusing for them.

The knitr package has something similar.  They use `kable()` to print data frames, but if a user wants kable to be used by default to print all data frames in R markdown, they need to load the printr package.  By keeping them separate, we can all use knitr without changing the default printing behavior inadvertently.

What do you think? 

````r
---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(gtsummary)
trial %>% select(age, grade) %>% tbl_summary() 

head(mtcars)
```
````

**Comment by hughjonesd** [comment]
Did you try it? ;-)

**Comment by ddsjoberg** [comment]
Oh goodness! I was still on 4.7.1.  In 4.7.1.9000 it works properly! Sorry about that!
