### ISSUE TITLE
Allowed special characters in `sheet` argument to as_Workbook() produce error, but the function still produces expected results

### ISSUE THREAD

**Issue by jsavn** [hughjonesd/huxtable#157]
There's an issue with using special characters (that are allowed by Excel, as far as I can tell) in the `sheet` argument to `huxtable::as_Workbook()`.

The sheet gets added but an error is returned, saying `Error: Sheet X does not exist.`  (with X being the sheet used)

Here's a minimal example, using huxtable version 4.7.1, R version 4.0.0 and RStudio 
version 1.2.5042 on Windows 10:

```
library(huxtable)
wb <- openxlsx::createWorkbook()

wb <- as_Workbook(jams,
                  Workbook = wb, sheet = "sheet 1")  # this works as expected

wb <- as_Workbook(jams,
                  Workbook = wb, sheet = "sheet & 2")  # this will return an error, however...
print(wb)  # this correctly shows the added sheet!

wb <- as_Workbook(jams,
                  Workbook = wb, sheet = "sheet < 3")  # also produces error!
print(wb)  # this correctly shows the added sheet!
```

This is perplexing and breaks my pipelines at the minute - I only updated to `4.7.1` today and not sure what version I was on previously, sorry.

**Comment by jsavn** [comment]
I think this is actually an issue with `openxlsx`, trying the above creates the requested sheets, but doesn't write data to them. The following returns the same error:
```
wb <- openxlsx::createWorkbook()
openxlsx::addWorksheet(wb, sheet = "a < 1")  # this works
openxlsx::writeData(wb, sheet = "a < 1", jams)  # this returns an error
```

**Comment by hughjonesd** [comment]
Thank you for the bug report and investigative work!
