### ISSUE TITLE
Chinese font cannot be displayed correctly from rmarkdown to RTF

### ISSUE THREAD

**Issue by kaigu1990** [hughjonesd/huxtable#158]
Before using this form, please read `?"huxtable-FAQ"`. In particular:

**PLEASE DON'T USE GITHUB ISSUES FOR HELP REQUESTS.**

Github issues are for bug reports and feature requests only. If you have a help request, post it to e.g. stackoverflow or community.rstudio.com, and drop me an email with the link. I will try to help out, and this will benefit other users. Help requests found here will be closed with a short response, which is not guaranteed to be polite.

OK? On with the show.

**Describe the bug**
When I use rmarkdown in Rstudio and display table in RTF document, I find the chinese font can not be showed correctly.

**Minimal Reproducible Example**
The code in Rmarkdown is below:

```{r echo=FALSE, message=FALSE}
library(huxtable)
library(dplyr)
ht <- hux(
  Employee     = c('John Smith中文', 'Jane Doe中文', 'David Hugh-Jones'),
  Salary       = c(50000L, 50000L, 40000L),
  add_colnames = TRUE
)
ht  %>%
  set_right_padding(1)           %>%
  set_left_padding(1)            %>% 
  set_bold(1, 1:2, TRUE)          %>%
  set_top_border(1, 1:2, 1)    %>%
  set_bottom_border(1, 1:2, 1)    %>%
  set_bottom_border(4, 1:2, 1)    %>%
  set_align(1:3, 2, 'right')      %>%
  set_width(1) %>%
  set_number_format(2)            %>% 
  # set_font(1:4, 1:2, value = "Courier New") %>%
  set_font(1:4, 1:2, value = "Times New Roman") %>%
  set_font_size(1:4, 1:2, value = 9) %>%
  set_caption('1.1 Employee table') %>%
  set_caption_pos("topleft")
```

The total rmd code can be download: 
[testTest.txt](https://github.com/hughjonesd/huxtable/files/4769922/testTest.txt)

**Expected behavior**
Chinese font display correctly, like below:
![image](https://user-images.githubusercontent.com/22772592/84488532-eac35180-acd2-11ea-882e-1aef99274530.png)
 

**System details**
Please report the output of `packageVersion("huxtable")`, as well as your R version and Rstudio version if applicable.
`> packageVersion("huxtable")
[1] ‘4.7.1.9000’`

Thanks!

**Comment by hughjonesd** [comment]
Hi Kaigu,

Thank you for this helpful bug report. 

Please could you test the branch I have just uploaded, called "handle-utf8-in-rtf". You can do this as follows:

```
remotes::install_github("hughjonesd/huxtable@handle-utf8-in-rtf")
```

I hope this will work. If you could try it and report back, I may be able to include this bugfix for 5.0.0!

Cheers,
David

**Comment by kaigu1990** [comment]
Hi, David

Thank you for your update. I have reinstalled my package and try it again, but it's not getting better. Chinese font is still Incorrect in RTF like below:

![image](https://user-images.githubusercontent.com/22772592/84568511-84adfb80-adb2-11ea-8386-11c222c239c8.png)

But it displays correctly in rmarkdown when I render it in Rstuido

![image](https://user-images.githubusercontent.com/22772592/84568555-c63ea680-adb2-11ea-804e-d14c122edee6.png)

My package has been updated:

![image](https://user-images.githubusercontent.com/22772592/84568464-40226000-adb2-11ea-852d-ab9ed45911d1.png)

Thanks!

**Comment by hughjonesd** [comment]
Hi Kaigu,
Did you update it from github using the command I pasted? Could you show
the output of packageVersion("huxtable")?
Thanks,
David

**Comment by hughjonesd** [comment]
It might also help if you tell me your version of Word, the OS you are using, and the output of `Sys.getlocale()`.

**Comment by kaigu1990** [comment]
Hi, David

I update the package by your command.
The version of huxtable is below:
```
> packageVersion("huxtable")
[1] ‘4.7.1.9000’
```
I use Word 2016 in win10 and output of `Sys.getlocale()` is below:
```
> Sys.getlocale()
[1] "LC_COLLATE=Chinese (Simplified)_China.936;LC_CTYPE=Chinese (Simplified)_China.936;LC_MONETARY=Chinese (Simplified)_China.936;LC_NUMERIC=C;LC_TIME=Chinese (Simplified)_China.936"
```
If you have any questions please let me know. Thanks!

**Comment by hughjonesd** [comment]
Thanks once again. Could you paste in  the following and give me the output?

```
# note 3 colons below, not 2
huxtable:::utf8_to_rtf(matrix("John Smith中文", 1, 1))
# also
Encoding("John Smith中文")
```

Lastly, if you could attach the rtf file that is the output of your rmd file above, that would also be very helpful.

**Comment by kaigu1990** [comment]
I enter your command and the output is below:
```
> huxtable:::utf8_to_rtf(matrix("John Smith中文", 1, 1))
     [,1]            
[1,] "John Smith中文"
> Encoding("John Smith中文")
[1] "unknown"
```
And the RTF file can be download from [test111.rtf](https://www.bioinfo-scrounger.com/data/test111.rtf)

If you have any questions please let me know. 
Thanks!
Kai

**Comment by hughjonesd** [comment]
OK. I've pushed an updated version to the same branch. If you reinstall again with `install_github("hughjonesd/huxtable@handle-utf8-in-rtf")` then... it may work. Or it may not! 

If it doesn't work, and if you feel confident, you could try debugging `utf8_to_rtf()` yourself:

```
library(huxtable)
debugonce(huxtable:::utf8_to_rtf)
huxtable:::utf8_to_rtf("John Smith中文")
```

which will then launch you into the interactive debugger. (See ?browser for how to use it.)

**Comment by kaigu1990** [comment]
Hi, David

Thanks a lot! It's amazing that it's ok now. The chinese font can be displayed well in RTF.
Huxtable package is very suitable in my project so I'm very looking forward to this. I'd like to write a blog to introduce it, especially in RTF report with rmarkdown.

Thanks again!
Kai

**Comment by hughjonesd** [comment]
Brilliant, thanks a lot for your help debugging.

Do by all means write a blog! Rweekly might like to hear about it. If you drop me an email I will put it on twitter.

**Comment by kaigu1990** [comment]
Hi, David

Thank you for your debugging. 
But I find the question is still on the footnote, like `add_footnote("* 考核试剂：双通道中有一个阳性即可判定为阳性，对比试剂：双通道中两个均为阳性才可判定为阳性", border = 1)`. It can be seen from RTF document, the chinese footnote is not normal display.

By the way, as I mentioned before, I'd like to post blog to introduce `huxtable` package, is the email(davidhughjones@gmail.com) yours, or could you tell me your email here if convenient ? You can also view it directly at https://www.bioinfo-scrounger.com/archives/Using-huxtables/.

Thanks!
Kai

**Comment by hughjonesd** [comment]
Hi Kai

If I run

```
library(huxtable)
ht <- hux("A cell")
ht <- add_footnote(ht, "* 考核试剂：双通道中有一个阳性即可判定为阳性，对比试剂：双通道中两个均为阳性才可判定为阳性")
quick_rtf(ht)
```

I get Chinese displayed. Is there something wrong with how it looks?

That's my email, sure – I guess you aren't going to put it in the blog though!

**Comment by hughjonesd** [comment]
You might want to submit that blog as an international resource to rweekly.org.

**Comment by kaigu1990** [comment]
Hi, David

There are some incorrect words in this sentence. You can run
```
ht <- hux("A cell")
ht <- add_footnote(ht, "* 中文试剂")
quick_rtf(ht)
```
The "中文" word is correct, but "诖剂" word should be "试剂". So maybe there is some problems in encoding.
Please let me know if there is someting I could do to help you debugging.

And thanks for you recommendation, I have submitted my blog to rweekly.org. It's my first to use rweekly, everything looks interesting. After this blog is accepted I will tell you in time.

Thanks again!
Kai

**Comment by hughjonesd** [comment]
If you could try github master now, I hope this is corrected. Many thanks for the careful testing. I will do a bugfix release in a few weeks.

**Comment by kaigu1990** [comment]
Hi, David

Thank you for your help.  So quickly you are, It's ok now.

Kai
