### ISSUE TITLE
error_pos = "same": significance stars after p-value in brackets

### ISSUE THREAD

**Issue by ChrisWaloszek** [hughjonesd/huxtable#161]
When using `error_pos = "same"`, the standard errors are displayed in the same cell as the estimates.
However, the significance stars are located *before* the p-value in brackets, such that the estimates are not very nicely aligned:

      huxreg(lm1, lm3, error_pos = "same")
                      (1)                     (2)
      (Intercept)     981.607 (720.175)        6.269 *** (0.782)
      carat           4328.324 *** (136.755)   3.531 *** (0.149)
      depth           -27.785 * (11.656)       -0.019 (0.013)
      N               100                      100    
      R2              0.912                    0.854
      *** p < 0.001; ** p < 0.01; * p < 0.05.

To improve the alignment when using `error_pos = "same"`, would it be possible to have the significance stars after the brackets? I.e. to have something more like the following:

       huxreg(lm1, lm3, error_pos = "same")
                      (1)                     (2)
      (Intercept)     981.607 (720.175)        6.269 (0.782) *** 
      carat           4328.324 (136.755) ***   3.531 (0.149) ***
      depth           -27.785 (11.656) *       -0.019 (0.013)
      N               100                      100    
      R2              0.912                    0.854
      *** p < 0.001; ** p < 0.01; * p < 0.05.

**Comment by hughjonesd** [comment]
Interesting. In general, putting stars after the estimate rather than the
standard error seems to be the standard.

* If you want better alignment, why not just use error_pos = "right"?
* Would it be enough to make a variable "{stars}" available for glue()ing
within error_format?

**Comment by ChrisWaloszek** [comment]
Truly the standard is different. When using `error_pos = "same"` the estimate, stars, and p-value appear very close to another which is nice.
When using `error_pos = "right"` the p-value appears more to the right as all columns are spaced equally.
Would it be an alternative solution to use `error_pos = "same"` but with all cell contents aligned to the decimal of the estimate? Including the statistics below?

**Comment by hughjonesd** [comment]
There I think `error_pos = "below"` would do it. Or you could tweak column
spacing with `*_padding` properties.

**Comment by ChrisWaloszek** [comment]
With the number of variables in the table, `error_pos = "below"` makes my tables very long and too long to display on a single page in landscape format.

**Comment by hughjonesd** [comment]
Sorry; I think this is just too much of a special case for `huxreg()` to deal with. I recommend using padding to get what you want.
