### ISSUE TITLE
Group estimates in regression table

### ISSUE THREAD

**Issue by ChrisWaloszek** [hughjonesd/huxtable#162]
Would it be possible to group together certain estimates to distinguish between treatment and control variables in a regression? Below an attempt with `rowspan()` which did not get very far (first rows for my somehow no longer shown in the table).

      data(diamonds, package = "ggplot2")
      diamonds <- diamonds[1:100,]
      
      lm1 <- lm(price ~ carat + depth, diamonds)
      lm2 <- lm(price ~ depth + factor(color, ordered = FALSE), diamonds)
      lm3 <- lm(log(price) ~ carat + depth, diamonds)
      
      color_names <- grep("factor", names(coef(lm2)), value = TRUE)
      names(color_names) <- gsub(".*)(.)", "Color: \\1", color_names)
      
      hux <- huxreg(lm1, lm2, lm3, coefs = c("Carat" = "carat", "Depth" = "depth", color_names))
      rowspan(hux)[1, 1:4] <- 4
      hux

**Comment by hughjonesd** [comment]
Certainly possible, but I don't plan to include facilities within huxreg to
do this. It is simpler to use standard huxtable editing.

**Comment by ChrisWaloszek** [comment]
Thank you for the info. How would that look alike for the above example?

**Comment by hughjonesd** [comment]
See the manual for how to insert rows and columns. For your example, I'm not sure what you are trying to do, but indeed if you make rowspan 4 for the top row, then rows 2-4 will be hidden.
