### ISSUE TITLE
huxreg notes don't wrap in LaTeX

### ISSUE THREAD

**Issue by ramattheis** [hughjonesd/huxtable#164]
**Describe the bug**

`print_latex` doesn't wrap long notes in huxreg tables. 

**Minimal Reproducible Example**

`longnote = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ipsum nulla, pellentesque eu tellus eu, sodales congue nulla. Sed varius lacus ac nisl rutrum, id feugiat odio facilisis. "`
`data(diamonds, package = "ggplot2")`
`huxreg(lm(price~carat,diamonds), 
       note = longnote) %>% 
  print_latex()`

**Expected behavior**

Long table notes should be inside of a `tablenotes` environment, as in earlier versions, and not in a `\multicolumn`.

**System details**

`packageVersion("huxtable")`
`[1] ‘5.0.0’`

**Comment by hughjonesd** [comment]
The reason for this is that in version 5.0.0, `width` is no longer set. Set `width` and you will find the note wraps. Huxtable has never used tablenotes, incidentally, though perhaps it should.
