### ISSUE TITLE
Use as_Workbook to write huxtable to a particular cell location in Excel

### ISSUE THREAD

**Issue by aranryan** [hughjonesd/huxtable#167]
Perhaps I've missed it, but I don't see how to supply a cell location as an argument to as_Workbook. For example, in openxlsx it is possible to specify a starting column and row for a table. For example:

writeData(wb, 2, x = "Iris dataset group means", startCol = 2, startRow = 2)

I am considering writing huxtables to several sheets in a workbook, and would like to be able to start them in maybe the third column over, 10 rows down.

**Comment by hughjonesd** [comment]
Try github master in a few minutes.

**Comment by hughjonesd** [comment]
Try github master in a few minutes.
