### ISSUE TITLE
huxtable causes printing of data.table := 

### ISSUE THREAD

**Issue by sjewo** [hughjonesd/huxtable#168]
**Describe the bug**

After loading the `huxtable` package a invisible returned `data.table` is printed.

`data.table` has a special operator `dt[, newvar := NA]` to create a new variable inside of a data.table. Similar to `dt$newvar <- NA` the function call prints no result (neither in a R console or markdown).

After loading `huxtable`, the use of the  `:= ` operator causes the printing of the whole `data.table` (see the following example).

This might be related to: https://github.com/rstudio/rmarkdown/issues/829

**Minimal Reproducible Example**

I could reproduce the error with latest `data.table`,  `huxtable` and `rmarkdown` packages.

~~~~~~~~~~~~~~~~~~~~~~~
```{r setup, include = FALSE}
library(data.table)
#library(huxtable) # remove comment to see the bug
```

```{r a}
# This should result in no table output
cars <- data.table(cars)
cars[ , test := rnorm(50)] 
cars[test > 0 , test2 := rnorm(.N)] 
```

```{r}
# This should result in no output
wide <- dcast(cars, speed ~ dist)
wide[, speed2 := factor(speed)]
```
~~~~~~~~~~~~~~~~~~~~~~~

**Expected behavior**

I would expect, that no table is produced after using the `:=`-operator.

**System details**
```
> packageVersion("huxtable")
[1] ‘5.0.0.9000’
> packageVersion("data.table")
[1] ‘1.12.8’
> packageVersion("rmarkdown")
[1] ‘2.3.2’
> packageVersion("knitr")
[1] ‘1.29’
```
```
> R.version
               _
platform       x86_64-pc-linux-gnu
arch           x86_64
os             linux-gnu
system         x86_64, linux-gnu
status
major          4
minor          0.2
year           2020
month          06
day            22
svn rev        78730
language       R
version.string R version 4.0.2 (2020-06-22)
nickname       Taking Off Again

```

**Comment by sjewo** [comment]
I applied the patch used in `rmarkdown` and it seems to fix this issue: 
https://github.com/sjewo/huxtable/commit/59d4c9a2ce78dc7ff1f11c7277b1d931627bfd61

**Comment by hughjonesd** [comment]
A simpler workaround would be to set `options(huxtable.knit_print_df = FALSE)`. See `?huxtable-options`.

**Comment by sjewo** [comment]
That is the workaround I use at the moment (after I found out, that `huxtable` causes this behavior). 

If you don't want to add specific changes for `data.tables`, adding this workaround to your FAQ  might be helpful for other users.

**Comment by hughjonesd** [comment]
Thanks. Yup, I've added this to the FAQ.
