### ISSUE TITLE
huxtables don't work in beamer

### ISSUE THREAD

**Issue by ramattheis** [hughjonesd/huxtable#169]
**Describe what is missing**

Huxreg tables in beamer either don't render nicely or may break. In particular, the \hhline doesn't render. 

Here's an example: 

R code: 
```
require(huxtable)
data(cars)
hxt = huxreg(lm(speed ~ dist, cars))
write(to_latex(hxt), file = "~/test.txt" )
```

Beamer Code: 
```
\documentclass{beamer}

\usepackage{array}
\usepackage{caption}
\usepackage{graphicx}
\usepackage{siunitx}
\usepackage{ulem}
\usepackage{colortbl}
\usepackage{multirow}
\usepackage{hhline}
\usepackage{calc}
\usepackage{tabularx}
\usepackage{threeparttable}
\usepackage{wrapfig}
\usepackage{adjustbox}

\begin{document}

\begin{frame}{Table test}

  \input{test.txt}

\end{frame}

\end{document}

```

Output: 

![image](https://user-images.githubusercontent.com/31579035/86523864-d93c1800-be40-11ea-990d-8f7a1328c2e3.png)

**Describe your proposed solution**

It would be wonderful if huxreg tables worked in beamer as they do in LaTeX, more generally. Perhaps this is an issue with beamer? 

Thanks so much!

**Comment by hughjonesd** [comment]
Interesting. Is there a reason you're doing it this way rather than via Rmarkdown? Does it look different if you do it via rmarkdown?

**Comment by ramattheis** [comment]
Mostly because this is my old workflow (and that of collaborators). I think it would be ideal to be able to render the table from the same file in both latex and beamer.

The html output of huxreg in Rmarkdown looks great, but I can't get this to work for pdf/beamer. Likely related, I'm failing to generate the pdf vignette from the original huxtabl.Rmd. I get the error: `! Undefined control sequence. l.211 \FloatBarrier`

Apologies if this is an issue on my end!

**Comment by hughjonesd** [comment]
If you could attach the rmarkdown that doesn't work for you that would be great.

The huxtable.Rmd needs a file called placeins-header.tex in the same directory, containing the lines:

```
\usepackage{placeins}
\usepackage{pmboxdraw}
```

**Comment by hughjonesd** [comment]
I get an error from the following:

```
---
title: "Untitled"
author: "David Hugh-Jones"
date: "27/10/2017"
output: 
  beamer_presentation:
    keep_tex: true
---

````{r table1hux, echo = FALSE}

library(huxtable)

huxreg(lm(speed ~ dist, cars))
# replace this line by three backticks :-)

```

The reason is that `beamer_presentation` ignores LaTeX dependencies.

**Comment by hughjonesd** [comment]
This would best be fixed at rmarkdown level, since it affects any code using `latex_dependency()`: @yihui might have some thoughts.

**Comment by hughjonesd** [comment]
Actually it's a bit more complicated than that. The mwe still fails even if you include the dependencies. The reason is this:

https://tex.stackexchange.com/questions/420448/error-illegal-parameter-number-in-definition-of-iterate/420454

Oh boy. **TeX Must Die.**

**Comment by hughjonesd** [comment]
The workaround is to replace # with #### in `\providecommand`. I'll think if this is implementable in huxtable.
```
  \providecommand{\huxb}[2]{\arrayrulecolor[RGB]{####1}\global\arrayrulewidth=####2pt}
  \providecommand{\huxvb}[2]{\color[RGB]{####1}\vrule width ####2pt}
  \providecommand{\huxtpad}[1]{\rule{0pt}{####1}}
  \providecommand{\huxbpad}[1]{\rule[-####1]{0pt}{####1}}
```

The other part of the workaround is to add the LaTeX dependencies from `report_latex_dependencies()` manually:

```
header-includes:
  - \usepackage{array}
  - \usepackage{caption}
  - \usepackage{graphicx}
  - \usepackage{siunitx}
  - \usepackage{ulem}
  - \usepackage{colortbl}
  - \usepackage{multirow}
  - \usepackage{hhline}
  - \usepackage{calc}
  - \usepackage{tabularx}
  - \usepackage{threeparttable}
  - \usepackage{wrapfig}
  - \usepackage{adjustbox}
```

Thanks for this bug report - and incidentally, thanks for supporting me on Patreon! I didn't make the connection until today.

**Comment by hughjonesd** [comment]
Another option: use the `fragile` option to beamer `\frame`. Not sure this is doable from rmarkdown though.

**Comment by hughjonesd** [comment]
Aha! Pandoc respects the .fragile option, so you can do this:

    
    # A slide {.fragile}

    ```{r table1hux, echo = FALSE}
    library(huxtable)
    huxreg(lm(speed ~ dist, cars))
    ```

and the huxtable will appear. Still no horizontal lines though.

**Comment by ramattheis** [comment]
**TeX must die**, indeed. This has been great motivation to move away from beamer. 

Thanks so much for these work-arounds! 

I'm still getting an error in generating a pdf version of `huxtable.Rmd` though this might be a TeX issue on my end: `Package fontspec Error: The font "LucidaConsole" cannot be found.`

**Comment by hughjonesd** [comment]
That means what it says; you don't have that font installed, but are setting it somewhere, and presumably have set `options(huxtable.use_fontspec=TRUE)`. But it's a different bug, if it is a bug at all.
