### ISSUE TITLE
style_cells(ht, set_bold = TRUE) errors with "could not find function" if huxtable package isn't attached

### ISSUE THREAD

**Issue by igelstorm** [hughjonesd/huxtable#171]
**Describe the bug**
If huxtable is used without attaching the package with `library(huxtable)`, the `style_cells` function errors under some circumstances, specifically when trying to set the `bold` property &ndash; see example below.

By using the package without attaching it, I mean either explicitly prefixing every function call with `huxtable::`, or only attaching the desired functions with `import::here` or `import::from` from the [import package](https://cran.r-project.org/web/packages/import/vignettes/import.html). As far as I can tell, the vast majority of huxtable's functionality works perfectly fine used like this, so I'm guessing that this is not an intentional limitation.

Avoiding `library()` in favour of more explicitly declaring where functions come from is recommended (or hinted at) in a few influential sources ([Google](https://google.github.io/styleguide/Rguide.html#qualifying-namespaces), [Hadley Wickham](http://r-pkgs.had.co.nz/description.html#dependencies)), so it would be nice to support this usage for people who prefer/need it. Alternatively, if for any technical reason the package *needs* to be attached with `library()` this might be worth highlighting somewhere in the docs?

**Minimal Reproducible Example**
Both of the examples below error, with the message `could not find function "set_bold"`.

```{r}
ht <- huxtable::hux(a = c(1,2,3))
ht <- huxtable::style_cells(ht, bold = TRUE)
```

```{r}
import::from(huxtable, "hux", "style_cells")

ht <- hux(a = c(1,2,3))
ht <- style_cells(ht, bold = TRUE)
```

**Expected behavior**
I expected this not to error. Either of the below examples works:
```{r}
library(huxtable)
ht <- huxtable::hux(a = c(1,2,3))
ht <- huxtable::style_cells(ht, bold = TRUE)
```

```{r}
import::from(huxtable, "hux", "style_cells", "set_bold")
ht <- hux(a = c(1,2,3))
ht <- style_cells(ht, bold = TRUE)
```

**System details**

```
> packageVersion("huxtable")
[1] ‘5.0.0’
> version$version.string
[1] "R version 4.0.0 (2020-04-24)"
```

**Comment by hughjonesd** [comment]
Yup, this is a legit bug.

**Comment by hughjonesd** [comment]
Could you try with github master?

**Comment by igelstorm** [comment]
That was quick &ndash; thanks! I just tried with the latest master, and can confirm that it seems to be fixed.
