### ISSUE TITLE
(pdf)latex: Hyphenation Issue With First Word of a Paragraph

### ISSUE THREAD

**Issue by panporter** [hughjonesd/huxtable#173]
First: Thank you for your great effort producing this very mature table package (for LaTeX _and_ HTML).

**Describe the bug**
(pdf)latex has an issue with hyphenating the very first word of a paragraph. That leads to a broken cell wrapping if the first word is too long. Unfortunately a word in a table cell happens to be too long quite frequently. (At least in my use cases and native language.)

See:
LaTeX Problem: https://tex.stackexchange.com/questions/478691/table-data-crosses-the-column

LaTeX Solution: https://tex.stackexchange.com/a/348411

A workaround, as mentioned above, is to use `\nobreak\hspace{0pt}` before the very first word. (I'm not sure if it applies to the end of the paragraph as well.) `\nobreak` prevents a line break at the beginning.

**Minimal Reproducible Example**

```
---
title: "MWE"
output: pdf_document
---

```{r}
library("huxtable")
df <- data.frame(
  Column_1 = c("uncharacteristically is such a long word", "an uncharacteristically long text that is wrapped and hyphenated correctly"),
  Column_2 = c( 10, 20),
  Column_3 = c( 10, 20),
  Column_4 = c( 10, 20),
  Column_5 = c( 10, 20),
  Column_6 = c( 10, 20),
  Column_7 = c( 10, 20)
)

ht <- huxtable(df)
width(ht) <- 1
wrap(ht) <- TRUE

theme_plain(ht)
```

produces PDF

![broken hyphenation](https://user-images.githubusercontent.com/68369549/87638424-0c857d80-c744-11ea-8b27-d90cf0e59530.png)

**Expected behavior**
Hyphenation for every word in a cell.

![correct hyphenation](https://user-images.githubusercontent.com/68369549/87639966-4c4d6480-c746-11ea-9f9d-cbbfa98ee9c5.png)

I ended up compiling an intermediate huxtable version locally adding `\nobreak\hspace{0pt}` too each cell. But I wasn't quite sure, where to put it. Finally put it in latex.R l. 317, but seems a bit ugly to me:

```
inner_cell_bldc <- paste0(tpad_tex_bldc, align_tex_bldc, lpad_tex_bldc, "\\nobreak\\hspace{0pt}", inner_cell_bldc, "\\nobreak\\hspace{0pt}",
        rpad_tex_bldc, bpad_tex_bldc)
```

**System details**
packageVersion("huxtable"): ‘5.0.0’
R version 3.6.3 (2020-02-29)
RStudio Version 1.3.959
pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020)

**Comment by hughjonesd** [comment]
Could you add `\nobreak\hspace{0pt}` at the start of your content, and set `escape_contents` to `FALSE`? I am wary of huxtable trying to fix every bug in LaTeX.

**Comment by hughjonesd** [comment]
Closing for now.

**Comment by panporter** [comment]
Thanks for your suggestion.
I have now a function `sanitize_latex_huxtable(ht)` that adds `\nobreak\hspace{0pt}` to each cell and sanitizes the content if `escape_contents` is `TRUE` setting all `escape_contents` to `FALSE` afterwards.

But how do I hook this into the `to_latex()` function?

If I don't do this, I have to remember to call `sanitize_latex_huxtable(ht)` each time I want to output the table (and take care of not messing up HTML tables and the like).

**Comment by hughjonesd** [comment]
The easiest thing might be to create a subclass.

**Comment by mstackhouse** [comment]
@panporter would you be able to share your `sanitize_latex_huxtable()` function? I'm having similar issues where this would help.

**Comment by panporter** [comment]
Sorry for the late reply, @mstackhouse.

I ended up monkey patching huxtable's sanitize() function since this is the last function applied to the cell's content before inserting into the latex table's cell.

The following code is to be loaded after loading the huxtable package via `library("huxtable")`. Additionally package _R.utils_ is required.

```r
#issue: first word in cell does not get hyphenated
#see: https://github.com/hughjonesd/huxtable/issues/173
#solution: monkey patching sanitization function of package huxtable. requires package R.utils
#for monkey patching (overriding/replacing a given function) in R see: https://stat.ethz.ch/pipermail/r-help/2008-August/171321.html

#do nothing if fix already applied
if (! exists("huxtableFIXownSanitize", mode = "function") ) {
        #save original sanitize function for later use
        huxtableFIXoriginalSanitize <- huxtable:::sanitize

        #new function that passes everything on to the original function
        huxtableFIXownSanitize <- function (str, type) {
                result <- huxtableFIXoriginalSanitize(str, type)

                #in case of latex sanitization: pre- and append fix for correct hyphenation
                if (type == "latex") result <- paste0("\\nobreak\\hspace{0pt}", result, "\\nobreak\\hspace{0pt}")
                result
        }

        #replace original function with new one
        R.utils::reassignInPackage("sanitize", pkgName = "huxtable", huxtableFIXownSanitize)
}
```

Feel free to reuse and comment.
