### ISSUE TITLE
Shouldn't convert to scientific notation the numbers inside huxreg notes.

### ISSUE THREAD

**Issue by vladtarko** [hughjonesd/huxtable#174]
If you have a number inside the note, like a year, it gets converted to scientific notation. 

**Example**
```{r}
library(huxtable)
m <- lm(mpg ~ hp + wt + cyl, data = mtcars)
huxreg(m, note = "{stars}. Data from 1974 Motor Trend US magazine (Henderson and Velleman 1981)")
```

The note is converted to: "Data from 1.97e+03 Motor Trend US magazine (Henderson and Velleman 1.98e+03)".

**Expected behavior**
The note should be shown as introduced.

**System details**
huxtable version: 4.7.1
R version: 4.0.0

**Comment by hughjonesd** [comment]
Try github master now.

>

**Comment by vladtarko** [comment]
Thanks!
