### ISSUE TITLE
Huxtable clashes with with knitr & render_listings()

### ISSUE THREAD

**Issue by NbSdI** [hughjonesd/huxtable#176]
`\documentclass[twoside,nobib]{tufte-book}

\begin{document}

<<setup, include = FALSE, cache = FALSE>>=
render_listings()
library(tidyverse)
library(huxtable)
@
%%%%%%%%%%

<<string>>=
N <- tibble(N = c( '1', '2', '3'))
N
@

\end{document}`

When I compile this with knitr I get

> > ! Package inputenc Error: Unicode character â (U+250C)
> (inputenc)                not set up for use with LaTeX.
> 
> See the inputenc package documentation for explanation.
> Type  H <return>  for immediate help.
>  ...                                              
>                                                   
> l.33                                â
>                                        âââââââââââââ...
> 

$platform
[1] "x86_64-apple-darwin17.0"
$version.string
[1] "R version 4.0.2 (2020-06-22)"

**Comment by hughjonesd** [comment]
In general for a knitr document, you are going to need to print the huxtable dependencies. See `report_latex_dependencies()` and the vignette. Also, I can't use this reprex - it requires numerous additional LaTeX packages to be installed. If you still think this is a legit bug, please provide a minimal reprex.

**Comment by hughjonesd** [comment]
OK, I've installed these packages, and if I run

 Rscript -e 'library(knitr);knit("tmp.Rnw")'
pdflatex tmp.tex

then I get a working PDF, though for some reason it doesn't show the R output, only the program.

**Comment by NbSdI** [comment]
Hi David,

I now can’t reproduce the problem even including everything I have in my main source files for the book

My source files:


Output:


I’m mystified, and I apologize,
Michael
