### ISSUE TITLE
merge_repeated_rows merges cell below an NA

### ISSUE THREAD

**Issue by misea** [hughjonesd/huxtable#183]
**Describe the bug**
When calling merge_repeated_rows, the cell below an NA appears to be merged even if it is not NA

**Minimal Reproducible Example**
```r
tribble_hux(~a, ~b, 
             1, NA_character_, 
             2, "hello", 
             3, "goodbye") %>% 
  merge_repeated_rows()
```

**Expected behavior**
In the example above, I expected "hello" in column 2 of the output, instead of having that cell merged with the blank one above. I expected repeated NA cells to be merged, but any non NA cell below not to be merged. 

**System details**
Package version: 5.0.0, R version:  4.0.2 (2020-06-22),  Rstudio version: 1.3.959 (Mac)

**Comment by hughjonesd** [comment]
Fixed in master. Please try.
