### ISSUE TITLE
Trouble with display of 2-ways interactions object returned by sim_slopes

### ISSUE THREAD

**Issue by CdeMills** [hughjonesd/huxtable#185]
**Describe the bug**
While generating tables for 2x2 interactions, each one with three levels, the resulting table is mixed

**Minimal Reproducible Example**
I was following the example at 
https://cran.r-project.org/web/packages/interactions/vignettes/interactions.html

library(survey)
data(api) 
dstrat <- svydesign(id = ~1, strata = ~stype, weights = ~pw, 
                     data = apistrat, fpc = ~fpc)
regmodel3 <- svyglm(api00 ~ avg.ed * growth * enroll, design = dstrat)
library(interactions)
ss3=sim_slopes(regmodel3, pred = growth, modx = avg.ed, mod2 = enroll)
library(huxtable)
as_huxtable(ss3)

The result is a first level with two entries, the second with three, the last one with four. The first entry of the second level is the third entry of the first level.
 
**Expected behavior**
see https://cran.r-project.org/web/packages/interactions/vignettes/interactions.html
scroll down to the box with as_huxtable(ss3)
The result is a table with three main entries, each containing three sublevels

**System details**
system: CentOS-8 x86_64
 packageVersion("huxtable")
[1] ‘5.0.0.9000’

R version 4.0.2 (2020-06-22) -- "Taking Off Again"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

Any hint ?
Regards
Pascal Dupuis

**Comment by hughjonesd** [comment]
Isn’t this an issue with the “interactions“ library?

**Comment by CdeMills** [comment]
Well, the mentioned web page is dated April, 4th, 2020. Not that long ago, and their example seems working. The package interactions was released at the same date, while huxtable was release on June, 15th. Maybe some change between huxtable v5/0 (the one I use) and the one available at the beginning of April ?

Not sent from my IPhone. I don't have an IPhone.

**Comment by CdeMills** [comment]
Dear,

I confirm that installing the version tagged 'v4.7.1-rc2' from github results in said example running fine.
─────────────────────────────────────
  enroll = 153.05                    
  Value of avg.ed   Slope of growth  
─────────────────────────────────────
  2.09              1.25 (0.32)***   
  2.79              0.39 (0.22)#     
  3.49              -0.48 (0.35)     
─────────────────────────────────────
  enroll = 595.28                    
  Value of avg.ed   Slope of growth  
─────────────────────────────────────
  2.09              0.72 (0.22)**    
  2.79              0.34 (0.16)*     
  3.49              -0.04 (0.24)     
─────────────────────────────────────
  enroll = 1037.51                   
  Value of avg.ed   Slope of growth  
─────────────────────────────────────
  2.09              0.18 (0.31)      
  2.79              0.29 (0.20)      
  3.49              0.40 (0.27)   

The issue is thus linked to the changes in v5.0.0-rc1

Regards
Pascal

**Comment by hughjonesd** [comment]
Good bug hunting. However, I still think it’s an interactions bug prima facie, until there’s evidence of a bug in the underlying huxtable code being called.

**Comment by CdeMills** [comment]
Facts tell me:
1) huxtable 4.7.1-rc2 didn't trigger the issue
2) huxtable 5.0.0 does
3) interactions was released between 4.7.1-rc2 and 5.0.0

So maybe it's an issue with the interactions package. Yet this new behavior was introduced by the changes in huxtable.  Any chance of narrowing it down with "git bisect" ?
Regards

Pascal

**Comment by CdeMills** [comment]
Did the bug hunting through bisection. It was introduced in:

5577d69f906c277e32ad96f358c9a5d4c05b6adc is the first bad commit
commit 5577d69f906c277e32ad96f358c9a5d4c05b6adc
Author: David Hugh-Jones <davidhughjones@gmail.com>
Date:   Fri May 1 15:51:42 2020 +0100

    Big changes:
      - width becomes NA by default
      - wrap is ignored in TeX if width is NA
      - use tabular not tabularx if possible
      - add_colnames becomes TRUE by default

The issue is probably within;
 R/html.R                                           |   9 ++-
 R/huxreg.R                                         |   6 +-
 R/huxtable.R                                       |  10 +--
 R/latex.R                                          |  18 +++--
 R/properties.R                                     |  18 +++--
 R/rtf.R                                            |   5 +-
 R/zzz.R                                            |   6 +-

Regards
Pascal

**Comment by CdeMills** [comment]
With the 5.0.0-rc2 release, the given example fails as reported. But setting
options(huxtable.add_colnames = FALSE)
make it work and generates:

   ─────────────────────────────────────
                       enroll = 153                       
                       Value of avg.ed   Slope of growth  
                     ─────────────────────────────────────
                       2.09              1.25 (0.32)***   
                       2.79              0.39 (0.22)#     
                       3.49              -0.48 (0.35)     
                     ─────────────────────────────────────
                       enroll = 595.28                    
                       Value of avg.ed   Slope of growth  
                     ─────────────────────────────────────
                       2.09              0.72 (0.22)**    
                       2.79              0.34 (0.16)*     
                       3.49              -0.04 (0.24)     
                     ─────────────────────────────────────
                       enroll = 1037.51                   
                       Value of avg.ed   Slope of growth  
                     ─────────────────────────────────────
                       2.09              0.18 (0.31)      
                       2.79              0.29 (0.20)      
                       3.49              0.40 (0.27)   

Regards

Pascal

**Comment by CdeMills** [comment]
To summarize:
buggy behavior:
                  ─────────────────────────────────────
                    enroll = 153                       
                    Value of avg.ed   Slope of growth  
                  ─────────────────────────────────────
                    Value of avg.ed   slope            
                    2.09              1.25 (0.32)***   
                    2.79              0.39 (0.22)#     
                  ─────────────────────────────────────
correct behavior:
                  ─────────────────────────────────────
                    enroll = 153                       
                    Value of avg.ed   Slope of growth  
                  ─────────────────────────────────────
                    2.09              1.25 (0.32)***   
                    2.79              0.39 (0.22)#     
                    3.49              -0.48 (0.35)     
                  ─────────────────────────────────────
Differences: "Value of avg.ed   slope" as first line of the first group of data, shifting the results down by one line. The last group of data contains one supplemental element.

IMHO, it this colnames line has to be present, it should make the first group of data higher by one line.

Regards

Pascal

**Comment by hughjonesd** [comment]
@jacob-long could you take a look at this? It looks like something due to having add_colnames=TRUE by default in 5.0.0.
