### ISSUE TITLE
CRAN Check Failure for Upcoming broom Release

### ISSUE THREAD

**Issue by simonpcouch** [hughjonesd/huxtable#186]
Hey there!

The broom dev team just ran reverse dependency checks for the upcoming broom 0.7.1 release and came across a new issue in your package. I've pasted the results below:

```
     ERROR
    Running the tests in ‘tests/testthat.R’ failed.
    Last 13 lines of output:
      > test_check("huxtable")
      ── 1. Failure: huxreg works when nobs not available (@test-huxreg.R#170)  ──────
      `huxreg(ct, statistics = NULL)` did not produce any warnings.
      # weights:  9 (4 variable)
      initial  value 35.155593 
      iter  10 value 23.131901
      final  value 23.129234 
      converged
      ══ testthat results  ═══════════════════════════════════════════════════════════
      [ OK: 1159 | SKIPPED: 19 | WARNINGS: 1 | FAILED: 1 ]
      1. Failure: huxreg works when nobs not available (@test-huxreg.R#170) 
      Error: testthat unit tests failed
      Execution halted
    
```

The unit test fails because of lines 164-6 in `test-huxreg.R`:

```
  m <- lm(Sepal.Width ~ Sepal.Length, data = iris)
  ct <- lmtest::coeftest(m)
  expect_warning(huxreg(ct, statistics = NULL), "No glance method")
```

As of 0.7.1, broom supplies a glance method for `coeftest` objects! That was an unexpected breaking change from our end. :-)

We hope to submit this new version of the package to CRAN in the coming weeks. If you encounter any problems fixing this issue, please feel free to reach out.

**Comment by hughjonesd** [comment]
Thanks guys - easy to fix.

**Comment by hughjonesd** [comment]
Could you guys suggest to me any objects that do have tidy() but don't have
glance()?

>

**Comment by SHAESEN2** [comment]
Survfit objects are one of them from the survival package.

**Comment by hughjonesd** [comment]
Fixed in github. I'll update after you guys release, having updated recently.

**Comment by simonpcouch** [comment]
Much appreciated!
