### ISSUE TITLE
remove colnames printing

### ISSUE THREAD

**Issue by maRce10** [hughjonesd/huxtable#188]
Before using this form, please read `?"huxtable-FAQ"`. In particular:

**PLEASE DON'T USE GITHUB ISSUES FOR HELP REQUESTS.**

Github issues are for bug reports and feature requests only. If you have a help request, post it to e.g. stackoverflow or community.rstudio.com, and drop me an email with the link. I will try to help out, and this will benefit other users. Help requests found here will be closed with a short response, which is not guaranteed to be polite.

OK? On with the show.

**Describe what is missing**
What problem does this feature solve? Or, what would this feature enable the user to do that they can't do currently? Or, how would this feature make using huxtable easier?

**Describe your proposed solution**
A clear and concise description of what you want to happen. Give code examples if that helps.

**Target audience**
What set of people would this feature benefit?

**Additional context**
Add any other context about the feature request here.

**Comment by hughjonesd** [comment]
???

**Comment by maRce10** [comment]
![Captura de ecrã de 2020-12-08 08-54-57](https://user-images.githubusercontent.com/13245502/101504208-907d1380-3938-11eb-97f8-fa3e462ba015.png)

**Comment by hughjonesd** [comment]
Hi Marce, 

Please read the text that you simply left in the original bug report. Then file an actual bug report or feature request, as the text indicates. If English is not your first language, then get someone to help.
