### ISSUE TITLE
remove printing of column names when printing an object of class huxtable

### ISSUE THREAD

**Issue by maRce10** [hughjonesd/huxtable#189]
Hi Hugh

Very  cool package indeed! It would be great if you could add an option to remove the printing of the column names at the bottom of the table when printing an object of class huxtable, as shown in this image:

![Captura de ecrã de 2020-12-08 08-54-57](https://user-images.githubusercontent.com/13245502/101515017-857bb080-3943-11eb-9ff1-21091d3966a3.png)

thanks

Marcelo

**Comment by hughjonesd** [comment]
Hi Marcelo,
Can you say who is likely to need this feature and why?

**Comment by hughjonesd** [comment]
More to the point, this already exists in `print_screen()`. Just set `colnames = FALSE`. If you want this to be true every time you evaluate a huxtable in the console,  just set:

```
options(huxtable.print = function (h) {
   print_screen(h, colnames = FALSE)
  cat("\n")
})
```

See `?huxtable-options` and `?print_screen` for more info.

**Comment by maRce10** [comment]
Hi 

 I actually wonder the same for the printing of the column names at the bottom. This is the first data formatting package that does that. So people is used to not having them printed.

**Comment by maRce10** [comment]
thanks

**Comment by maRce10** [comment]
> More to the point, this already exists in `print_screen()`. Just set `colnames = FALSE`. If you want this to be true every time you evaluate a huxtable in the console, just set:
> 
> ```
> options(huxtable.print = function (h) {
>    print_screen(h, colnames = FALSE)
>   cat("\n")
> })
> ```
> 
> See `?huxtable-options` and `?print_screen` for more info.

ok so the answer was a easy one, thanks
