### ISSUE TITLE
Latex tables with borders for multicolumn cells

### ISSUE THREAD

**Issue by ninohardt** [hughjonesd/huxtable#192]
**Problem**
Latex tables in academic papers often contain many columns that need to be organized. 

Example:
Let's say I have this very simple data.frame called `my_df` turned into a huxtable `my_ht`:
```r
library(huxtable)
library(tidyverse)

my_df = data.frame(A=1:4, B=5:8, alpha=10:13, beta=100:103)
my_ht = huxtable(my_df)
```
There are two kinds of columns. Those with Latin colnames, and those with Greek colnames. It is easy to add multicolumn elements:
```r
my_ht %>% 
  insert_row(c('Latin','Latin', 'Greek', 'Greek')) %>%
  merge_cells(c(1,1),c(1,2)) %>% merge_cells(c(1,1),c(3,4))
```
Additionally, some hline and cline equivalents should be applied.
```r
my_ht %>% 
  insert_row(c('Latin','Latin', 'Greek', 'Greek')) %>%
  merge_cells(c(1,1),c(1,2)) %>% merge_cells(c(1,1),c(3,4)) %>%
  set_bottom_border(row = c(1,1) , col = 1:2,   brdr(1, "solid", "black")) %>% 
  set_bottom_border(row = c(1,1) , col = 3:4,   brdr(1, "solid", "black")) %>%
  set_bottom_border(row = c(2,2) , col = 1:4,   brdr(1, "solid", "black")) %>%
  set_right_padding(row = 1 ,col =2, 10 ) %>%
  quick_latex()
```
![image](https://user-images.githubusercontent.com/4387287/106060802-866acc00-60c2-11eb-9daf-7a59c1791bbe.png)

That's nice, but I need a little 'gap' to help the reader. The borders need to be trimmed. It should look like this:
![image](https://user-images.githubusercontent.com/4387287/106060982-c3cf5980-60c2-11eb-9ba1-b115a2af3f1f.png)

What does NOT work is using padding or adding a white-colored border:
```r
my_ht %>% 
  insert_row(c('Latin','Latin', 'Greek', 'Greek')) %>%
  merge_cells(c(1,1),c(1,2)) %>% merge_cells(c(1,1),c(3,4)) %>%
  set_bottom_border(row = c(1,1) , col = 1:2,   brdr(1, "solid", "black")) %>% 
  set_bottom_border(row = c(1,1) , col = 3:4,   brdr(1, "solid", "black")) %>%
  set_bottom_border(row = c(2,2) , col = 1:4,   brdr(1, "solid", "black")) %>%
  set_right_padding(row = 1 ,col =2, 10 ) %>%
  set_right_border(row = 1 ,col =2, brdr(1, "solid", "white")) %>%
  quick_latex()
```

**Solution**

See latest post

**Comment by hughjonesd** [comment]
I'd love to do this but I suspect it is very diffocult to write the correct LaTeX programmatically. Will consider. Thanks for the feature request.

**Comment by ninohardt** [comment]
Yes, this is going to be difficult. I hope you can leave this issue open, and hopefully someone can come up with some ideas.

Using the extracolsep approach (let's call it that), you would probably need additional attributes:

- An attribute for extracolsep, analogue to `set_left_border`. It would be ignored for html outputs and only used for latex outputs
- Another one for top/bottom/midrule, because those are the lines not broken by extracolsep. If applied to a cell, this should supersede `set_bottom_border` information
- Something that lets `_border` be turned into \cline instead of \hhline - though that might not be necessary

One can modify existing huxtable output manually, so it should also be possible programmatically. However, it adds complexity and attributes that only apply to Latex exports.

Ideally, there would be another technique in Latex to create those gaps between borders.

**Comment by hughjonesd** [comment]
I don't like separate interfaces for different kinds of output. Ideally something like (HTML's) spacing attributes (which add space outside borders) might work. But do you know how to implement this in TeX? In particular, I use hhline because it works nicely with line colours, multiple widths and double lines; IIRC cline may not be as flexible.

If you're interested in working on this, and know a lot of TeX, I'd be open to working on a PR.

**Comment by ninohardt** [comment]
Separate interfaces aren't desirable, I agree. While I am interested in working on this, I don't have a good solution strategy yet. There's two challenges:

1. The Latex code for this (It's clunky working directly in TeX)
2. How to tell huxtable to put a gap in a way that leads to consistent outputs, whether it is html or tex or whatever

Ideally, there would be a single extra attribute to add gaps/spacing, and it translates to the corresponding implementation in latex or html. The problem in latex is that it would affect several parts of the output code, which makes it hard to programmatically.

**Comment by hughjonesd** [comment]
If you can figure out ways to do it in LaTeX, I can integrate it.

**Comment by ninohardt** [comment]
Thanks! I updated the initial post to minimize clutter. It's mostly figured out.

**Comment by ninohardt** [comment]
How to move to `booktabs`:

Let's say I have this very simple data.frame called `my_df` turned into a huxtable `my_ht`:
```r
library(huxtable)
library(tidyverse)

my_df = data.frame(A=1:4, B=5:8, alpha=10:13, beta=100:103)
my_ht = huxtable(my_df)
```

There are two kinds of columns. Those with Latin colnames, and those with Greek colnames. It is easy to add multicolumn elements:
```r
my_ht %>% 
  insert_row(c('Latin','Latin', 'Greek', 'Greek')) %>%
  merge_cells(c(1,1),c(1,2)) %>% merge_cells(c(1,1),c(3,4))
```

This generates the tex output:

```r
my_ht %>% 
  insert_row(c('Latin','Latin', 'Greek', 'Greek')) %>%
  merge_cells(c(1,1),c(1,2)) %>% merge_cells(c(1,1),c(3,4)) %>%
  set_bottom_border(row = c(1,1) , col = 1:2,   brdr(1, "solid", "black")) %>% 
  set_bottom_border(row = c(1,1) , col = 3:4,   brdr(1, "solid", "black")) %>%
  set_bottom_border(row = c(2,2) , col = 1:4,   brdr(1, "solid", "black")) %>%
  set_right_padding(row = 1 ,col =2, 10 ) %>%
  quick_latex()
```

The border/rule exports as this:
```
\hhline{>{\huxb{0, 0, 0}{1}}->{\huxb{0, 0, 0}{1}}->{\huxb{0, 0, 0}{1}}->{\huxb{0, 0, 0}{1}}-}
\arrayrulecolor{black}
```

There are two elements here: `\hhline`  once for each line and `\huxb` for each cell.

With booktable, we don't need an overarching `\hhline` equivalent. For each cell, the change works as follows:

Instead of 
```
\huxb{RGB}{width}
``` 
it is
```
\corcmidrule[width]\arrayrulecolor{RGB}\cmidrule[width](trim){1-1} 
```
where

*  `[width]` needs to be in pt or em or whatever fit
* `(trim)` is omitted or l, r, or lr. 
* `{1-1}` is always there because it is created programmatically cell-by-cell. The number need to reflect the position of the cell. So it's 1-1, 2-2, 3-3, ...
* `RGB` is the color

This also required a macro `\corcmidrule`, defined somewhere at the top of the tex file:
```tex
\newcommand{\corcmidrule}[1][2pt]{% \corcmidrule[<len>]
	\\[\dimexpr-\normalbaselineskip-\belowrulesep-\aboverulesep-#1\relax]%
}
```
(this has been described here: https://tex.stackexchange.com/questions/522639/cmidrule-align-same-line-using-arraystretch)

Vertical lines are something that shouldn't be used in good looking tables, so I am not sure what do about them.

**Comment by ninohardt** [comment]
Here is the modified `.tex` file from the above example:

[tex-from-hux.zip](https://github.com/hughjonesd/huxtable/files/5894859/tex-from-hux.zip)

**Comment by hughjonesd** [comment]
This is an interesting approach. 

Can it cope with varying the border width and/or colour within a given row? (It looks as if that _should_ be fine, but have you tried?) 

Does it offer doubled lines? Dotted and/or dashed? (At the moment we don't have those in TeX, but they'd be nice.)

Can anything be done about vertical lines? They may well be bad looking, but that depends on context (e.g. soft vertical borders can be nice on the web; sometimes you want to emphasize the symmetry of rows and columns; etc.) and anyway, they're a stable part of the API.

Here's a Rmd file which I often use for manual testing:
https://github.com/hughjonesd/huxtable/blob/master/scripts/table-tester-2.Rmd

**Comment by ninohardt** [comment]
(1) varying widths
I just tested it and realized (a) there should be no `\corcmidrule` before the first `\cmidrule` - the positioning will already be correct and (b) it 'works' with varying widths, but the rules are aligned with respect to the lowest position, not the highest. I will look into this. It might just be a change to the macro to fix this.

(2) double and vertical rules.
Let me quote the [booktabs package documentation](https://mirrors.concertpass.com/tex-archive/macros/latex/contrib/booktabs/booktabs.pdf)
![image](https://user-images.githubusercontent.com/4387287/106360556-0a9d9900-62e7-11eb-8bfa-a5e0d9ba300a.png)

Oh well....

Maybe there are ways to do it, but before we look into that, it should be decided if that makes sense.

I think it is great that your package can take the same table with a lot of different properties and turn it into many different outputs, including .html and .tex and more. The new ambitious `gt` package is great for html tables, but really does not work well at all for tex tables. huxtable is much better for tex output. However, there are limits to 100% consistency between the outputs.

One idea would be to have `to_latex` and a new `to_latex_booktabs` functions for export. The booktabs version would omit vertical and double rules, but be able to handle widths and colors and all that. The `to_latex` version would have vertical rules, but no trimming.

This would still be very helpful for many workflows. One can design tables, just modify certain properties for format-specific outputs and then export to .tex, .html and whatnot accordingly.

**Comment by ninohardt** [comment]
I think varying width are no problem. A quick update on how to do this programmatically.

Instead of 
```
\huxb{RGB}{width}
``` 
The first element in a row is:
```
\arrayrulecolor{RGB}\cmidrule[width](trim){1-1} 
```
All subsequent ones are:
```
\corcmidrule[widthPrev]\arrayrulecolor{RGB}\cmidrule[width](trim){1-1} 
```
where

*  `[widthPrev]` width of the PREVIOUS rule
*  `[width]` width of current rule element; needs to be in pt or em or whatever fit
* `(trim)` is omitted or l, r, or lr. 
* `{1-1}` is always there because it is created programmatically cell-by-cell. The number need to reflect the position of the cell. So it's 1-1, 2-2, 3-3, ...
* `RGB` is the color

The macro `\corcmidrule`, defined somewhere at the top of the tex file, does not need to be changed.
```tex
\newcommand{\corcmidrule}[1][2pt]{% \corcmidrule[<len>]
	\\[\dimexpr-\normalbaselineskip-\belowrulesep-\aboverulesep-#1\relax]%
}
```
I also thought about adjusting the macro, but I think it's quite easy to implement as described.

Minimal example to play with:
```tex
\documentclass{article}
\usepackage{colortbl}
\usepackage{booktabs} 

\newcommand{\corcmidrule}[1][2pt]{% \corcmidrule[<len>]
	\\[\dimexpr-\normalbaselineskip-\belowrulesep-\aboverulesep-#1\relax]%
}

\begin{document}
\newcommand{\corcmidrule}[1][2pt]{% \corcmidrule[<len>]
	\\[\dimexpr-\normalbaselineskip-\belowrulesep-\aboverulesep-#1\relax]%
}

\begin{table}[ht]
	\begin{tabular}{lllll}
		\toprule
		A & B & alpha & beta & gamma\\
		\arrayrulecolor{black}\cmidrule[1pt](l){1-1} 
		\corcmidrule[1pt]\arrayrulecolor{black}\cmidrule[2pt](){2-2} 
		\corcmidrule[2pt]\arrayrulecolor{black}\cmidrule[2pt](){3-3} 
		\corcmidrule[2pt]\arrayrulecolor{black}\cmidrule[5pt](){4-4} 
		\corcmidrule[5pt]\arrayrulecolor{black}\cmidrule[1pt](){5-5}
		1 &	5 &	10 &	100 & 1\\
		2 &	6 &	11 &	101 & 1\\
		2 &	7 &	12 &	102 & 1\\
		3 &	8 &	13 &	103 & 1\\
		\bottomrule
	\end{tabular}
\end{table}

\end{document}
```

**Comment by hughjonesd** [comment]
I appreciate your feelings about vertical lines. Many people feel the same way.

If booktabs can't do vertical lines, then I'd still be open to a separate booktabs engine... but only if you do the work of coding the actual TeX creation. I can help with integration, but I'm not going to take on the main burden. *And* I'd have to be convinced first that the benefits outweigh the costs.

**Comment by hughjonesd** [comment]
Closing for now because I doubt this is going to happen.
