### ISSUE TITLE
Math formula in cell is not escaped in r markdown html output

### ISSUE THREAD

**Issue by petr-fedorov** [hughjonesd/huxtable#194]
Hello,
I'd expect that the output is the same in both chunks:

    ---
    title: "Test"
    output: html_document
    ---

    ```{r does not work}
    library(huxtable)
    ht <- huxtable(
            Text   = "x squared",
            Math  = "$x^2$",
            Form = c('My formula $\\sum_{i=1}^9$')
          )
    escape_contents(ht) <- FALSE
    ht
    ```

and

     ```{r works, results='asis'}
    library(huxtable)
    ht <- huxtable(
            Text   = "x squared",
            Math  = "$x^2$",
            Form = c('My formula $\\sum_{i=1}^9$')
          )
    print_html(ht)
    ```

But it is different:

![изображение](https://user-images.githubusercontent.com/949629/110965661-74d53f00-8365-11eb-8528-b3763cf8570c.png)

I use `R Studio` 1.2.5042  `huxtable` 5.2.0 and `knitr` 1.31 on Debian 10

**Comment by hughjonesd** [comment]
Hmm. Not sure if I can do much about this. 
Guess about what's happening: `print_html()` prints the raw HTML into the rmarkdown. rmarkdown then parses the TeX maths, even if the output is HTML. OTOH, printing the huxtable  calls `to_html` and then wraps it in HTML preserve.
Best option might be to try setting `options(print.huxtable = print_html)` or possibly `to_html`.

**Comment by petr-fedorov** [comment]
Here it is:

<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:does not work">
<col><col><col><tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Text</th><th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Math</th><th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Form</th></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">x squared</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">$x^2$</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">My formula $\sum_{i=1}^9$</td></tr>
</table>

<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:works">
<col>
<col>
<col>
<tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">
Text
</th>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">
Math
</th>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">
Form
</th>
</tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">
x squared
</td>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">
<span class="math inline">\(x^2\)</span>
</td>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">
My formula <span class="math inline">\(\sum_{i=1}^9\)</span>
</td>
</tr>
</table>

**Comment by petr-fedorov** [comment]
The code below works (I replaced "$" with "\\(" which is the same in LaTeX)

```{r works too}
library(huxtable)
ht <- huxtable(
        Text   = "x squared",
        Math  = "\\(x^2\\)",
        Form = c('My formula \\(\\sum_{i=1}^9\\)')
      )
ht
```

Generated HTML:
<table class="huxtable" style="border-collapse: collapse; border: 0px; margin-bottom: 2em; margin-top: 2em; ; margin-left: auto; margin-right: auto;  " id="tab:works too">
<col><col><col><tr>
<th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Text</th><th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Math</th><th style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">Form</th></tr>
<tr>
<td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">x squared</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">\(x^2\)</td><td style="vertical-align: top; text-align: left; white-space: normal; padding: 6pt 6pt 6pt 6pt; font-weight: normal;">My formula \(\sum_{i=1}^9\)</td></tr>
</table>

**Comment by hughjonesd** [comment]
OK, thanks for the report. I think your workaround is good enough and may point to it in documentation.
