### ISSUE TITLE
Using Latex math in caption and footnote

### ISSUE THREAD

**Issue by lakshmiraut** [hughjonesd/huxtable#197]
Is it possible to have Latex Math like $\int f(x) $ etc. in the caption and footnote, similar to knitr::kable capabilities? It is a great package otherwise.

**Comment by hughjonesd** [comment]
The footnote you can already do with `escape_contents`. For the caption see `?caption`.

**Comment by lakshmiraut** [comment]
> The footnote you can already do with `escape_contents`. For the caption see `?caption`.

sanitize or escape_content does not render latex formula such as $x^2$ as intended.  It escapes, i.e., you get the latex equation as it is.  My problem is to render latex equations in the header cells and in caption or footnotes.  I could not find any  help on the issue.

**Comment by hughjonesd** [comment]
```
hux("$x^2$") %>% set_escape_contents(FALSE) %>% quick_pdf()
```

works for me, what error are you getting?

**Comment by lakshmiraut** [comment]
First let me apologize for asking the same question as a separate issue. Since my first issue was not displayed on the issues board, I posted the second time. Not trying to spam, for which I have no time or interest.

your example works on R and it works when quick_pdf() is used but not for quick_docx() or quick_html() and limited to do it table by table instead of a whole R markdown document.   

I am trying to have latex equations in huxtable footnote, in a cell or in the caption. I use R Studio and Rmarkdown to prepare documents which can  create Latex/html/docx file with the appropriate output option.  Below I give the simplest example where you will see knitr::kable()  renders the table as expected but huxtable is not rendering the latex math. I have tried your example and it did not work in Rstudio.  Here is the content of my example Rmd file
=============
---
title: Huxtable exercise
output: html_document
---

To see working of latex equations in huxtable which works in knitr::kable


```{r table1, echo=FALSE,warning=FALSE}
library(huxtable)
library(dplyr)  
table1 <- data.frame("x"=c("$\\beta_0$","$\\beta_1$"),y=c(1.5,2.5))
colnames(table1) <- c("parameter", "$\\chi^2$")
cap="Showing if latex math equations like $x^2$ renders in caption"

huxtable1 <-huxtable(table1) %>% 
  set_caption(cap) %>%
  set_escape_contents(FALSE) 
huxtable1

knitrtable <-knitr::kable(table1,caption=cap)
knitrtable
```

**Comment by hughjonesd** [comment]
Ah, I understand. I don't think it's going to be possible. The reason is that huxtable renders itself in a markdown fenced block, which is always rendered as pure HTML/TeX/whatever. These other systems do something different, I think. The closest you might be able to do is use `print_md()`.
