### ISSUE TITLE
Latex math in caption, footnote and table cells

### ISSUE THREAD

**Issue by lakshmiraut** [hughjonesd/huxtable#198]
Is it possible someway or do you plan to implement feature that will allow one to use latex math such as $\int f(x) $ and more complex equations in huxtable caption, footnote text and variable names.  If it is already there, I will appreciate if you can point to some example or manual.

**Comment by hughjonesd** [comment]
You've reported this bug already, and I gave you an answer and closed the bug. Please don't spam the bug tracker. This is a bug tracker, not a helpdesk: please don't spam it.
