### ISSUE TITLE
Wrong formatting when using by_cases()

### ISSUE THREAD

**Issue by karol27** [hughjonesd/huxtable#200]
**Describe the bug**
Huxtable in R give wrong formatting when using by_cases().
When I run this:

```
(library(tidyverse)
df = data.frame(
    stringsAsFactors = FALSE,
              Type = c("a", "b", "c", "d"),
                 A = c(51, 5, 10, 155.5),
                 P1 = c(40.1, 50.5, 127.8, 216),
                 C = c(40, 45, 50, 255)
     )
library(huxtable)
ht = as_hux(df)
ht %>% map_text_color( row = 2:nrow(df), col = 2:3,
                    by_cases(. < 50 ~ "red")) %>%
  set_all_borders()
ht
```

I get table:
![table](https://user-images.githubusercontent.com/49245448/117414000-ec16f180-af16-11eb-8e62-d1eb62f6feb7.jpg)

The problem is that 127.8 is bigger than 50 so it shouldn't be red.

**System details**
huxtable_5.3.0
R version 4.0.5 /i386
R Studio 1.4.1106

**Comment by karol27** [comment]
Reason is not obvious because most of rows is proper formatted.
Adding cases has turned numbers to character(). A workaround is to use by_cases(as.numeric(.) < 50 ~ "red")

**Comment by hughjonesd** [comment]
I think this is a deep design bug, or at least a consequence of a deepd design decision. Not much to do. Another workaround: don't add column names till after you've done formatting:

```r
ht <- as_hux(df, add_colnames = FALSE)
ht %>% map_text_color( row = 2:nrow(df), col = 2:3,
                    by_cases(. < 50 ~ "red")) %>%
                    set_all_borders() %>%
                    add_colnames()

```
