### ISSUE TITLE
Bolded columns are misaligned in print_screen

### ISSUE THREAD

**Issue by karol27** [hughjonesd/huxtable#201]
**Describe the bug**
When column names are **bold** then column width with names is another than other rows.

**Minimal Reproducible Example**
```
library(tidyverse)
df = data.frame(
  stringsAsFactors = FALSE,
              Type = c("a", "b", "c", "d"),
                 AAAAAAAAAAAAAA = c(51, 5, 10, 155.5),
                 BBBBBBBBBBBBBB = c(40.1, 50.5, 127.8, 216),
                 CCCCCCCCCCCCCC = c(40, 45, 50, 255)
     )
library(huxtable)
ht = as_hux(df)
ht = ht %>% 
  theme_basic() %>%
  set_all_borders()
ht
```
![table](https://user-images.githubusercontent.com/49245448/117434472-01971600-af2d-11eb-8a27-9d8455a6fe4b.jpg)

**Expected behavior**
Vertical lines of borders are in the same line for row with names and values

**System details**
huxtable_5.3.0
R version 4.0.5 /i386
R Studio 1.4.1106

**Comment by karol27** [comment]
Table in R has this problem but in markdown is OK

**Comment by hughjonesd** [comment]
I think this may be an effect of your terminal font. Can you try a fixed width font in Rstudio and see what happens?

**Comment by karol27** [comment]
I see that in your tabel above row with name is not bold. Try to make it **bold**. The problem is only when font is bold.

**Comment by hughjonesd** [comment]
It was using your code which indeed makes the title bold. Just that the bold doesn't display when copy-pasted. Have you tried with a fixed-width font?

**Comment by hughjonesd** [comment]
Feel free to reopen if you think this is still a problem.
