### ISSUE TITLE
Align "center" doesn't work in print_screen()

### ISSUE THREAD

**Issue by karol27** [hughjonesd/huxtable#202]
**Describe the bug**
Align "center" don't work. Output is the same when align is right.

**Minimal Reproducible Example**
The table on the end of this website:
[https://hughjonesd.github.io/huxtable/reference/align.html](https://hughjonesd.github.io/huxtable/reference/align.html)

**Expected behavior**
Just to center align work

**System details**
huxtable_5.3.0
R version 4.0.5 /i386
R Studio 1.4.1106

**Comment by karol27** [comment]
Table in R has this problem but in markdown is OK

**Comment by hughjonesd** [comment]
Yeah:

```r
tmp <- hux(a = c("1", "111", "11111", "1111111"))
align(tmp) <- "center"
tmp
                                              a  
                                              1  
                                            111  
                                          11111  
                                        1111111  

Column names: a

```

Need to look into the horror of `to_screen` to figure this out :-(

**Comment by hughjonesd** [comment]
Fixed in master, thanks!
