### ISSUE TITLE
caption_pos(ht) doesn't work in knit to pdf

### ISSUE THREAD

**Issue by agustinggza** [hughjonesd/huxtable#206]
Thanks for your job. I think huxtable is a very good program and really useful.
My problem:
I want to put a caption on top and "caption_pos" or "set_caption_pos" work in html and word but not to pdf render; captions are always in bottom of table. Any idea?
Thanks for all.

**Comment by hughjonesd** [comment]
Can you provide a minimal reproducible example?

**Comment by agustinggza** [comment]
Pardon, I think that it was a common behavoir to pdf. I reviewed my code and solve this problem including the library name like this huxtable::set_caption_pos(ht, "topcenter"). Now, This one works fine for me.
Thank you.
