### ISSUE TITLE
Provide options as a list

### ISSUE THREAD

**Issue by bjornerstedt** [hughjonesd/huxtable#207]
Suggestion: The huxreg function would be easier to use if options could be provided as a list. 

Motivation: In teaching introductory econometrics, I want to specify a bunch of non-default options to huxreg. For new users this is a little too demanding.  I have found it useful to specify options to huxreg as a list in the setup chunk of the rmarkdown documents. This is also rather useful in documents with several regression tables, a little like setting Knitr options for chunk output. 

The main reason for needing this code is that huxreg does not work well with the lm_robust function of the estimatr package. huxreg shows a warning as lm_robust does not generate AIC. As we advise students to always use robust standard errors, huxreg behaves less well in a standard setting.

Here is my simple implementation.

```r
library(estimatr)
library(huxtable)

table_options = list(
  stars = c(`*` = 0.1, `**` = 0.05, `***` = 0.01), 
  statistics = c("N. obs." = "nobs", "Adj. R squared" = "adj.r.squared"),
  omit_coefs = "(Intercept)"
)

huxregsimple = function(..., options = list()) {
  do.call(huxreg, modifyList(list(...), options))
}
```
The code used for regression tables becomes

```r
l1 = lm_robust(hwy ~ year , data = mpg)
l2 = lm_robust(hwy ~ year + displ , data = mpg)
huxregsimple(l1, l2, options = table_options)
```

The code can of course be improved, for example allowing both a list of options and individual options that override those specified in the list.

**Comment by hughjonesd** [comment]
I understand the motivation but I think rolling your own version is the best approach. You might also consider `purrr::partial`.
