### ISSUE TITLE
Numbers in footnotes should not be converted to scientific notation

### ISSUE THREAD

**Issue by njbart** [hughjonesd/huxtable#208]
**Describe the bug**
If numbers, e.g., years, appear in a footnote, they get converted to scientific notation. They shouldn’t.

See also https://github.com/hughjonesd/huxtable/issues/174.

**Minimal Reproducible Example**
```
library(huxtable)
ht <- as_hux(mtcars[1:3,])
add_footnote(ht, "Data from 1974.")
```

**Actual behavior**
`Data from 1.97e+03.`

**Expected behavior**
`Data from 1974.`

**System details**
huxtable 5.4.0
R 4.1.0
RStudio 1.4.1717

**Comment by hughjonesd** [comment]
Workaround: set `number_format` to `NA` on the new row. You can do this like `add_footnote(ht, "Data from 1974.", number_format = NA)` I think the default should indeed set this, so leaving this bug open.

**Comment by hughjonesd** [comment]
Should be fixed in master.
