### ISSUE TITLE
Incompatibility between huxtable LaTeX multicol environment

### ISSUE THREAD

**Issue by psads-git** [hughjonesd/huxtable#210]
Huxtable does not output the tables when inside a `multicol` environment (pdf output from rmarkdown), even when using `tabular_only=T`.

Attached is a zip file with an example that demonstrates the issue.

Thanks in advance!

[huxtable_bug.zip](https://github.com/hughjonesd/huxtable/files/6862686/huxtable_bug.zip)

**Comment by hughjonesd** [comment]
Yeah, the \huxvb TeX command defined by huxtable doesn't play nice within \multicols. I don't think I can fix this.
