### ISSUE TITLE
Table with arrows pointing between cells / elements

### ISSUE THREAD

**Issue by larry77** [hughjonesd/huxtable#211]
Dear All,

This is not really about an issue: it is a question and if there is no answer then please consider it as a feature request.
I would like to use huxtable to make a simple table plot, but with arrows pointing from one element to another.
I mean something along the lines of this

https://tex.stackexchange.com/questions/163174/table-with-arrows-between-cells

with huxtable generating the latex code for me.
Is this doable at all?
Many thanks

**Comment by hughjonesd** [comment]
I think this is too niche to be a valuable huxtable feature. You might be able to do it by entering latex or tikz code into the table cells and setting `escape_contents = FALSE`
