### ISSUE TITLE
Bugs related to calculation of string width in huxtable

### ISSUE THREAD

**Issue by NikNakk** [hughjonesd/huxtable#213]
I've run into two annoying bugs that relate to the way that the huxtable package measures widths of strings when outputting to the screen. `ncharw`() is used which in turn calls `stringi::str_width`. This regards certain characters (e.g. the interpunct, ·, \U00B7) as being width 2. The first bug happens when the width calculated by `ncharw()` exceeds the value of `eff_width` but the number of characters does not. This leads to an infinite loop in this section of code in `character_matrix()`, starting at line 297 in the current version on GitHub:

``` r
while (any(ncharw(x) > eff_width)) {
    lx <- length(x)
    last <- x[lx]
    last <- c(substring(last, 1, eff_width), substring(last, eff_width + 1))
    x[lx:(lx + 1)] <- last
}
```

### Reprex of first bug

``` r
options(width = 200) # change to 100 to reproduce the bug
my_data <- as.data.frame(rep(list("8·0 (3·2 - 16·0)"), 5))
colnames(my_data) <- paste0("V", 1:ncol(my_data))
huxtable::as_hux(my_data)
```

                                       V1                    V2                    V3                    V4                    V5                   
                                       8·0 (3·2 - 16·0)      8·0 (3·2 - 16·0)      8·0 (3·2 - 16·0)      8·0 (3·2 - 16·0)      8·0 (3·2 - 16·0)     

Column names: V1, V2, V3, V4, V5

<sup>Created on 2021-08-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

## Second bug

I've spent less time on the second related bug, but it seems that the padding width in `to_screen.huxtable` can sometimes end up negative if the first bug isn't triggered, as demonstrated below:

### Reprex of second bug

``` r
options(width = 100)
my_data <- as.data.frame(rep(list("0·105 - 0·206)"), 10))
colnames(my_data) <- paste0("V", 1:ncol(my_data))
huxtable::as_hux(my_data)
#> Error in strrep(" ", pad_width): invalid 'times' value
```

<sup>Created on 2021-08-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

All of this is in huxtable 0.5.4 on R 4.1.0 under RStudio 1.4.1717.

**Comment by hughjonesd** [comment]
Thank you for the careful bug report. Will take a look.

**Comment by hughjonesd** [comment]
I don't get an infinite loop with your first reprex (and width = 100), using github master. I also don't reliably get the strrep error from your second reprex. (I saw it once! Dammit.) Can you check after `remotes::install_github("hughjonesd/huxtable")`? Thanks.

**Comment by hughjonesd** [comment]
Note that stringi 1.6.2 gives 
```
> stringi::stri_width("\U00B7")
[1] 1
```
So maybe the fix is just update stringi?

**Comment by kforner** [comment]
I've been hit by the second bug too. 
Maybe for safety replacehttps://github.com/hughjonesd/huxtable/blob/f60b75c6397b38f1ac36f623f6d5fb76da9f9ae1/R/screen.R#L159
`result <- paste0(strrep(" ", pad_width), result)`
by 
`result <- paste0(strrep(" ", max(0, pad_width)), result)`

**Comment by hughjonesd** [comment]
Have you got a reliable reprex?

**Comment by kforner** [comment]
Unfortunately I haven't. It currently happens on very big tables, full of custom attributes.
I'll try to minimize one if I can.
The rationale for my proposal is that, in any case we do not want a negative pad_width, being because of a bug, of a wrong version, or a combination of exotic parameters. So better to be safe. Maybe even better: test its negativity, and send a warning so that it does not go unnoticed.

My stringi version: **1.7.6**

**Comment by kforner** [comment]
So here's the reprex:
```r
library(huxtable)
df <- data.frame(col = strrep('A', 200))
ht <- as_hux(df)
to_screen(ht)
##--> OK

# but
to_screen(ht, max_width=200)
Error in strrep(" ", pad_width) : invalid 'times' value
```

**Comment by hughjonesd** [comment]
Thanks! Should be fixed in master.

**Comment by kforner** [comment]
Thanks, that actually fixed my problems. Tables are just fine now.

**Comment by hughjonesd** [comment]
Thanks. OK, I think it is reasonable just to rely on `fansi` to fix this. I've added a test and the current version seems to pass, can you confirm?
