### ISSUE TITLE
Bug Report: Error with Word output when mixing a blank cell in `insert_row()` with `set_markdown()`

### ISSUE THREAD

**Issue by ddsjoberg** [hughjonesd/huxtable#219]
Hey hey!

A user of gtsummary encountered an error when they specified a blank column header with Word output.

The header row is added with with `insert_row()`, and that is followed by `set_markdown()` and the error occurs in `set_markdown()`.

Here's an example, thanks!
````
---
output: word_document
---

```{r}
library(gtsummary)
tbla <- 
  trial %>%
  select(trt) %>%
  tbl_summary()
```

```{r}
tbla$table_body %>%
  dplyr::select(label, stat_0) %>%
  huxtable::as_huxtable(add_colnames = FALSE) %>%
  huxtable::insert_row(after = 0, label = "", stat_0 = "**N = 200**") %>%
  huxtable::set_markdown(
    row = 1L, col = huxtable::everywhere,
    value = TRUE
  )
```
````

This is the error:
```
Quitting from lines 15-23 (reprex_huxtable.Rmd) 
Error in rep(list(flatten_branch), n) : invalid 'times' argument
Calls: <Anonymous> ... lapply -> flatten_ast -> <Anonymous> -> map -> list2
Execution halted
```

**Comment by hughjonesd** [comment]
Hmm. When I run it using the current version (github master) it runs fine and I get:

                                                       N = 200    
                               Chemotherapy Treatment              
                               Drug A                   98 (49%)   
                               Drug B                   102 (51%)  

with appropriate markdown formatting.

Can you reproduce on your machine?

**Comment by hughjonesd** [comment]
OK, this comes if you call `ftExtra::as_paragraph_md(cell, .from = "commonmark+strikeout")` with an empty cell. Seems like a bug in ftExtra, I'll head over there.

**Comment by hughjonesd** [comment]
The workaround for now would be to replace the last line with:

```r
 huxtable::set_markdown(
    row = 1L, col = 2L,
    value = TRUE
  )
```
or more generally, only use `set_markdown` on non-empty cells.

**Comment by hughjonesd** [comment]
Fixed in ftExtra.
