### ISSUE TITLE
Custom themes?

### ISSUE THREAD

**Issue by jaminday** [hughjonesd/huxtable#22]
Any chance of building in a way to store a series of set_X() commands as a custom theme? I.e. store my own combination of settings so I can just call it for every table.

I find I mostly just want theme_article() but without the automatic bolding applied, so I end up adding the same boilerplate commands to every table to override the formatting.

Great package btw!

**Comment by hughjonesd** [comment]
How about:

my_theme <- function(ht) {
   # your commands here

  ht
}

which is exactly what the builtins do...
David

**Comment by jaminday** [comment]
Of course, my bad. Yep this is perfect, sorry for wasting your time. Thanks!

**Comment by hughjonesd** [comment]
Not at all. You might also consider using `set_default_properties`.
