### ISSUE TITLE
How to Insert A Line Break?

### ISSUE THREAD

**Issue by Amarakon55** [hughjonesd/huxtable#221]
I am outputting to pdf_document. Here is a table I created:

```r
name <- c("Norman", "Gilda", "Wilma", "Wompa")
animal <- c("Hamster", "Flamingo", "Duck", "Wompa")
food <- c("Crumbs Other", "Pink lemonade", "Bread", "Tears of his enemies")

animals <- data.frame(name, animal, food)

as_hux(animals) %>%
  set_escape_contents(TRUE) %>%
  theme_plain() %>%
  set_caption("Example Table") %>%
  set_caption_pos("topleft")
```

Where one of the cells shows "Crumbs Other", I want the word "Other" to be on a new line. In kable, I could just add \n and that would do it. But here that is not the case. How do I add a line break?

**Comment by hughjonesd** [comment]
This isn't a bug report, but a help request. I think there is an underlying bug, though, which is that the documentation doesn't make clear how to get wrapping to work.

**Comment by amarakon** [comment]
Sorry, I didn't know this issue page was only for bugs and not help. Could you show me where I can find help with this package? I checked the documentation, and the documentation about wrapping is very confusing indeed. How could I modify the code I posted to get a line break to work?

**Comment by hughjonesd** [comment]
That's weird, because when you open a bug report, it says:

>  Create a report to help us improve. **Not a bug or feature request? Please use e.g. Stackoverflow.** 

And then, in the bug report pane itself, it says:

> 
> Before using this form, please read `?"huxtable-FAQ"`. In particular:
> 
> **PLEASE DON'T USE GITHUB ISSUES FOR HELP REQUESTS.**
> 
> Github issues are for bug reports and feature requests only. If you have a help request, post it to e.g. stackoverflow or community.rstudio.com, and drop me an email with the link. I will try to help out, and this will benefit other users. Help requests found here will be closed with a short response, which is not guaranteed to be polite.
> 

Perhaps you can tell me how I could make this clearer? I thought it was pretty clear, but some people just seem unable to get it.
