### ISSUE TITLE
huxtable and quarto label/caption options

### ISSUE THREAD

**Issue by hughjonesd** [hughjonesd/huxtable#224]
Various issues combining huxtable labels and captions with quarto's built-ins:

    ---
    title: "test"
    format: pdf
    editor: visual
    ---

    ```{r}
    #| include: false
    library(huxtable)
    ```

    @tbl-iris shows up but cannot be cross-referenced.

    ```{r}
    mytab<- hux(head(iris, n = 1))
    label(mytab)<- "tbl-iris"
    caption(mytab)<- "My caption"
    mytab
    ```

Quarto label, huxtable caption mixed:

    ---
    title: "test"
    format: pdf
    editor: visual
    ---

    ```{r}
    #| include: false
    library(huxtable)
    ```

    @tbl-iris shows up and can be cross-referenced, but the caption is a subcaption

    ```{r}
    #| label: tbl-iris

    mytab<- hux(head(iris, n = 1))
    caption(mytab)<- "My caption"
    mytab
    ```

**Comment by hughjonesd** [comment]
Thanks to @ailich for reporting. 
A workaround for now is to use quarto labels and captions.

**Comment by hughjonesd** [comment]
State of play right now:

* Under HTML, no labels work; huxtable captions work, but become subcaptions if `#| label: ` is used. Quarto captions don't work.
* Under PDF, huxtable labels don't work; quarto labels do. Huxtable captions work but become subcaptions if `#| label:`  is used. Quarto captions work and override huxtable captions. (So you apparently can't get a functioning caption and subcaption...!)

**Comment by ailich** [comment]
@hughjonesd, just a note that at least with PDF, using both quarto labels and captions isn't a full workaround as that currently causes the "[ht]" to precede the table as in the original reported issue (hughjonesd/huxtable#223).

**Comment by hughjonesd** [comment]
I understand. But that issue is a separate one and will hopefully get fixed soon.
