### ISSUE TITLE
Set format to percent for percents instead of "general"

### ISSUE THREAD

**Issue by ZacharyGoldstein** [hughjonesd/huxtable#226]
Add logic here so that percents are formatted as percents instead of "general" - this will help avoid a warning message from Excel that occurs when numbers are saved as text: https://github.com/hughjonesd/huxtable/blob/b45663bd79c8711e23879e6dd7347fa1b6229e22/R/Workbook.R#L146

**Comment by hughjonesd** [comment]
Is the format just PERCENT? If so, try the fix in master.

**Comment by hughjonesd** [comment]
Hmm, I doubt this will work. If it's formatted as a percentage then all of the relevant contents will already be an R string. And we can't convert them manually. So Excel will continue to generate these warnings.

**Comment by ZacharyGoldstein** [comment]
Yeah I think you'd need to change it so percent formatting leaves it as numeric, not a string, and instead changes the formatting later on in the process.

**Comment by hughjonesd** [comment]
Sorry. Think this is a wontfix.
