### ISSUE TITLE
Bookdown epub output not recognised in huxtable

### ISSUE THREAD

**Issue by davidfoxcroft** [hughjonesd/huxtable#230]
I'm using bookdown to create a book in different output formats: gitbook, pdf and epub. The original format for the book is Rmarkdown with tables created using huxtable. 

html (gitbook) and latex (pdf) formats work fine, but huxtable doesn't recognise the epub output format so this breaks the build - see attached image. Could epub3 output be added to huxtable?

![2022-10-17_09-19](https://user-images.githubusercontent.com/5821185/196113183-36c64c39-53e1-4bbe-b03d-d87781300902.png)

**Comment by hughjonesd** [comment]
Have you tried just using `as_html()`? It seems that epubs use html internally.

**Comment by hughjonesd** [comment]
Closing. Please reopen if need be.
