### ISSUE TITLE
Can't explicitly set border width to 0

### ISSUE THREAD

**Issue by robchallen** [hughjonesd/huxtable#231]
**Describe the bug**
I want to set all the borders in a table to nothing. 
When I set the borders to zero using `huxtable::set_all_borders(value=0)` the resulting html has no border width attribute set, rather than a border width attribute set to zero. 
This works fine until HTML is rendered with CSS that adds a default border (pandoc does this for html_vignette), at which point it annoyingly has a border.
I can work around this by not using `rmarkdown::html_vignette`, and it is not an issue for vanilla `html_document`, but it would be nice to be able to explicitly set to zero rather than relying on the css defaults.

**Minimal Reproducible Example**
A html vignette:
```
---
output: rmarkdown::html_vignette
---

```{r}
library(tidyverse)
tibble(col="cell") %>% 
  huxtable::hux() %>%
  huxtable::set_all_borders(value = 0)
```<!-- how do you escape backticks in github markdown? --> 
```
result of knitting:
![image](https://user-images.githubusercontent.com/16591648/196708660-a01181ec-45e8-46fe-920f-2d070eb77b07.png)

**Expected behavior**
No borders.

**System details**
> packageVersion("huxtable")
[1] ‘5.5.0’

**Comment by hughjonesd** [comment]
Fair enough. This should be fixed in master, please confirm.

**Comment by robchallen** [comment]
Many thanks. Confirmed that is now working as I hoped in html_vignette after commit 3a59cbf.
By the way, thanks for the package, it is great.
