### ISSUE TITLE
Huxtable -> bookdown -> word caption numbering problem

### ISSUE THREAD

**Issue by jjanmaat** [hughjonesd/huxtable#233]
Hello,

I have a Rmarkdown document with multiple tables and figures.  Am using huxtable for the tables and bookdown::word_document2 in the knitr instructions.

I only get caption numbering for two of the tables and two of the figures.  The remainder have numberings of the form (#tab:chunk_name) immediately before the caption.  The two that are numbered are not the first two.  Have tried adding blank lines, adding lines and text between chunks, etc.  Nothing seems to change it.

Any suggestions?

Thanks.

**Comment by hughjonesd** [comment]
Can you provide a minimal reproducible example, please?

**Comment by jjanmaat** [comment]
Hope it is just something simple I am doing wrong, or just don't understand.

`> sessionInfo()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=C                 LC_CTYPE=English_Canada.utf8 LC_MONETARY=C               
[4] LC_NUMERIC=C                 LC_TIME=C                   
system code page: 65001

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] ggrepel_0.9.2     ggforce_0.4.1     cowplot_1.1.1     gridExtra_2.3     ggplot2_3.4.0    
 [6] foreach_1.5.2     rcompanion_2.4.18 huxtable_5.5.1    xtable_1.8-4      spdep_1.2-7      
[11] sf_1.0-9          spData_2.2.1      sp_1.5-1          logitr_0.8.0      dplyr_1.0.10     
[16] MASS_7.3-58.1    
`

Minimal example:

`---
title: "Demonstration"
author: "John Janmaat"
date: "`r Sys.Date()`"
output:
  word_document:
    bookdown::word_document2
  html_document:
    bookdown::html_document2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(huxtable)
```

```{r table 1, echo=FALSE}
ht <- huxtable(head(cars))
caption(ht) <- "First Table"
ht <- theme_article(ht)
ht
```



```{r table 2, echo=FALSE}
ht <- huxtable(tail(cars))
caption(ht) <- "Second Table"
ht <- theme_article(ht)
ht
```




```{r table 3, echo=FALSE}
ht <- huxtable(cars[sample(1:nrow(cars),6),])
caption(ht) <- "Third Table"
ht <- theme_article(ht)
ht
```




```{r table 4, echo=FALSE}
ht <- huxtable(cars[sample(1:nrow(cars),6),])
caption(ht) <- "Fourth Table"
ht <- theme_article(ht)
ht
```
`
[BookHuxExamp.docx](https://github.com/hughjonesd/huxtable/files/10142236/BookHuxExamp.docx)

**Comment by hughjonesd** [comment]
Thank you. So here, all the tables have this problem. One more thing: what version of officer are you using?

**Comment by hughjonesd** [comment]
And same question for flextable…

**Comment by hughjonesd** [comment]
One other simple question: have you set the option `huxtable.use_bookdown = TRUE`?

**Comment by jjanmaat** [comment]
Hello

To answer your questions.

Adding

library(huxtable)
options(huxtable.use_bookdown=TRUE)
options(huxtable.bookdown=TRUE)

didn’t change anything for the test script.  Had tried these with the original as well.

Office version is Microsoft Office Professional Plus 2019

flextable version is 0.8.3.

Thanks for looking into it.

John.

**Comment by hughjonesd** [comment]
You can solve your problem by using labels without spaces in. Replace `{r table 1, ...}` with `{r table1, ...}`, etc. and the tables will be numbered as usual.

I think this is probably not a bug, because nothing in knitr says that it is legitimate to embed a space within the chunk label (https://yihui.org/knitr/options/). Indeed, that page says "Try to avoid spaces, periods (.), and underscores (_) in chunk labels and paths."

**Comment by jjanmaat** [comment]
Hello David,

Thanks for responding.  Guess I should read the documentation more carefully!

John.
