### ISSUE TITLE
as_flextable(colnames_to_header = TRUE) without duplicating the header

### ISSUE THREAD

**Issue by PatrickRWright** [hughjonesd/huxtable#245]
**Describe what is missing**
Currently, if I run `as_flextable(colnames_to_header = TRUE)`, then the returned `flextable` will have what looks like a duplicate header at the very top of the table. As a user, when using `colnames_to_header = TRUE`, I do not expect this duplication and have no straight forward way of dealing with it natively.

**Describe your proposed solution**
I've been playing around a little and it looks to me like this (e.g. slicing row one out before conversion) workaround does the trick. Maybe this could be the standard when `colnames_to_header = TRUE` is used. Not sure if I'm missing something though and how this does or does not fit into the native setup of `huxtable`.

```r
library(dplyr)
huxflexiris <- huxtable::as_hux(iris) %>%
  slice(-1) %>%
  huxtable::as_flextable(colnames_to_header = TRUE)

huxflexiris
```

**Target audience**
Everyone interested in seamless conversion of huxtables to flextables.

**Additional context**
I am primarily working with `huxtable` objects, which I, however, need to translate to `flextable` objects for docx output purposes. Using `huxtable::as_flextable()` leaves me without a (technical) header, which is an issue for long tables because the headers do not roll over to the next docx page anymore. The alternative via `colnames_to_header = TRUE` leaves me with a duplicated header which is also not ideal.

**Comment by hughjonesd** [comment]
If you run `as_hux()`, which by default sets `add_colnames` to `TRUE`, and then run `as_flextable` with `colnames_to_header = TRUE`, you will indeed have added the column names twice. The solution is either to run `as_hux(add_colnames = FALSE)` or `as_flextable(colnames_to_header = FALSE)`.

**Comment by PatrickRWright** [comment]
If I don't have them in the huxtable (which is my primary object of use) though and then just want to transfer everything to a flextable at the end that's not exactly seamless. i.e. I would need to store the header somewhere and the add is later to the flextable.

**Comment by PatrickRWright** [comment]
Maybe more context helps: I'm working on dual Rmd outputs (html and docx). Up to now the focus has been on html and huxtable which works very nicely. However, when moving over to docx, flextables seem to work a bit better. Thus, I'm looking to transfer the infrastructure from html "easily" to docx. Hence my suggestion. Personally, I can use the workaround I suggested but I thought I'd leave the suggestion here.

**Comment by hughjonesd** [comment]
I'm still confused. Why can't you use `add_colnames()` and/or flextable functions to do what you want?

**Comment by PatrickRWright** [comment]
The ground truth for me right now is a finished huxtable (including a header i.e. first line of the huxtable), which I am translating to a flextable. That's how I ran into the scenario that I originally described and the supposed "quick" solution.

Applying the suggestions from this thread (thank you by the way I appreciate the input) will likely entail changes earlier in the development process for me. I'll need to dig a bit deeper in any case.
