### ISSUE TITLE
Underlining text with Pandoc disables alignment options 

### ISSUE THREAD

**Issue by mvanaman** [hughjonesd/huxtable#253]
With the following Quarto file, it seems that underlining text using Pandoc's underlining syntax turns off or otherwise interferes with huxtable's "wrapright" position option. In other words, the underlined text and all text that follows bleeds into the table. "wrapleft" seems off as well. I haven't tried other Pandoc formatting though; I don't know much about Pandoc, I only discovered this because I use R Markdown Visual Editor, which underlines using Pandoc. 

Note that using `\underline{}` instead seems to work fine. 

Probably not a huge deal, but people working in R Markdown Visual Editor might be thrown.

EDIT: Actually, using `\underline{}` DOES NOT work. However, only the underlined text bleeds into the table. So underlining text this way works as long as you make sure your table comes completely before or after the underlined text :)

EDIT 2: Italicizing and bolding with markdown both are fine.

````
---
title: "test"
format: pdf
editor: visual
---

```{r}
#| include: false
library(huxtable)
library(dplyr)
```

All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy.

```{r}
#| echo: false
ht <- huxtable(
        column1 = 1:5,
        column2 = letters[1:5]
      )
ht %>% set_position("wrapright")
```

[All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy.]{.underline} All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy. All work and no play makes Jack a dull boy.
```

**Comment by mvanaman** [comment]
Here's the rendered example:
<img width="755" alt="Screenshot 2024-02-11 at 1 21 25 PM" src="https://github.com/hughjonesd/huxtable/assets/40613941/04f93496-6c10-4a8c-af23-0c5cbcd45758">

**Comment by hughjonesd** [comment]
Yup, I get the same. Any syntax of the form `[]{}` seems to trigger it. So does `~~` strikethrough.

In the rendered TeX, simply changing `\textbf` to `\st` is enough to trigger the bug, so I guess it is a TeX thing.

**Comment by hughjonesd** [comment]
Heh. From the [wrapfig](https://ctan.org/pkg/wrapfig) documentation:

"You must not specify a wrapfigure in any type of list environment or or immediately before or immediately after one. It is OK to follow a list if there is a blank line
(\par) in between."

So, the workaround here is:

* Don't use spans, or strikethrough, directly before or after a wrapped huxtable.

Fixing the idiosyncracies of wrapfig is definitely out of scope, so I'm afraid this is a "wontfix"! Thank you for huxtable's most esoteric bug report yet.

**Comment by mvanaman** [comment]
Interesting, thank you for checking this out and nice find.
