### ISSUE TITLE
huxreg issues with felm object from lfe::felm

### ISSUE THREAD

**Issue by roboton** [hughjonesd/huxtable#26]
Great package!  I'd like to report an issue using huxreg on felm objects.  felm objects have no problems with broom::tidy:

> tidy(mdlGroup)
     term    estimate   std.error statistic      p.value
1 groupG1 0.006795107 0.002494202  2.724361 0.0064433668
2 groupG2 0.009430680 0.002622499  3.596067 0.0003231721
3 groupG3 0.006620490 0.002064475  3.206864 0.0013421950
> huxreg(mdlGroup)
Error in huxreg(mdlGroup) : Unrecognized statistics: logLik, AIC
Try setting "statistics" explicitly in the call to huxreg()
> huxreg(mdlGroup, statistics=c())
Error: all(sapply(value, function(x) is.numeric(x) || is.character(x) ||  .... is not TRUE

But when calling huxreg on the object I get the following stack trace:

> Error: all(sapply(value, function(x) is.numeric(x) || is.character(x) || .... is not TRUE
> 5. stop(sprintf(ngettext(length(r), "%s is not TRUE", "%s are not all TRUE"), ch), call. = FALSE, domain = NA)
> 4. stopifnot(all(sapply(value, function(x) is.numeric(x) || is.character(x) || is.function(x))))
> 3. `number_format<-.huxtable`(`*tmp*`, value = list(0, NULL, NULL, NULL, NULL, NULL, NULL, NULL))
> 2. `number_format<-`(`*tmp*`, value = list(0, NULL, NULL, NULL, NULL, NULL, NULL, NULL))
> 1. huxreg(mdlGroup, statistics = c())

**Comment by hughjonesd** [comment]
Should work now. If you want to have no statistics, do `statistics = character(0)`, which is different from `statistics = c()` as `c()` is `NULL`.

**Comment by roboton** [comment]
You are a fantastic man, thanks for your help, speedy response, and great work on this!  #1 is true and I have a tremendous amount of respect for you (not me) taking them on.
