### ISSUE TITLE
as_flextable has some kind of issue with huxreg output

### ISSUE THREAD

**Issue by jacob-long** [hughjonesd/huxtable#28]
Thanks for alerting me over on my jtools package about the 1.0.0 changes. I caught a problem with
`as_flextable` when the `huxtable` comes from `huxreg`.

Rather than explain, I'll just provide this reproducible example:

```r
set.seed(27101975)
dfr <- data.frame(a = rnorm(100), b = rnorm(100))
dfr$y <- dfr$a + rnorm(100)
lm1 <- lm(y ~ a, dfr)
lm2 <- lm(y ~ a + b, dfr)
glm1 <- glm(I(y > 0) ~ a, dfr, family = binomial)
as_flextable(huxreg(lm1, lm2, glm1))
```

If your results are like mine, then the cells in the flextable are filled with placeholders (e.g., `{{1}}`) rather than the actual values in the huxtable.

**Comment by hughjonesd** [comment]
Try in github now. Turns out flextable doesn't like syntactically invalid column names.

**Comment by jacob-long** [comment]
Works!
