### ISSUE TITLE
Graceful degradation if glance method is missing

### ISSUE THREAD

**Issue by grasshoppermouse** [hughjonesd/huxtable#3]
I got an error when I tried using huxreg for a model with a tidy method but no glance method (svyglm from the survey package).

Instead of throwing an error, would it be possible for huxreg to instead generate the reg table without summary stats (and maybe print a warning)?

It would also be neat if there were some mechanism to pass in custom summary stats, e.g., a custom function. So, summary stats from the glance method would always be available (if that method exists), as well as stats from a custom function, if provided.

**Comment by hughjonesd** [comment]
Interesting. Yes, that seems reasonable.

**Comment by hughjonesd** [comment]
For passing in custom summary stats, why not just:

```
regtable <- huxreg(list_of_models)
regtable <- rbind(regtable, sapply(list_of_models, custom_function))
```
?

**Comment by grasshoppermouse** [comment]
Makes sense. That's a nice advantage of basing everything on a data frame.

**Comment by hughjonesd** [comment]
:-) that's why i did it.

**Comment by hughjonesd** [comment]
Try now. It will still complain if you ask for the default summary statistics; just set statistics = 'nobs'. It may be better for the default just to be "whatever all the models have got", I'll think about that.

**Comment by grasshoppermouse** [comment]
> On Mar 15, 2017, at 11:11 AM, David Hugh-Jones <notifications@github.com> wrote:
> 
> Try now.

It worked. Thanks!

> It will still complain if you ask for the default summary statistics; just set statistics = 'nobs'. It may be better for the default just to be "whatever all the models have got", I'll think about that.

Yes, even though you told me to do this, I forgot, and thought it still wasn’t working at first.
