### ISSUE TITLE
Table prints off-center in Rmarkdown with PDF output

### ISSUE THREAD

**Issue by kstierhoff** [hughjonesd/huxtable#35]
Hi, 
When knitting to PDF, the huxtable is off-center. Is there a way to have it centered in the page? I apologize for no reproducible code, but can provide any additional info/files as needed. Interestingly, doing:
library(huxtable)
hux(summary(cars))
in a new .Rmd file is centered. Seems to be some padding on my hux object.
Thanks,
Kevin

![image](https://user-images.githubusercontent.com/2256746/33345350-efeb409a-d440-11e7-86f4-f5f73f0131ac.png)

**Comment by hughjonesd** [comment]
See ?position and ?width. I haven't found perfect solutions to this but setting the width right seems to be key.

**Comment by kstierhoff** [comment]
Yes, setting position(x) <- 'left' aligns it properly, but I must adjust (shorten) the column names to fit the table on the page. Thanks for the quick reply!
