### ISSUE TITLE
issues with conditional formatting

### ISSUE THREAD

**Issue by davarix** [hughjonesd/huxtable#41]
Hi,
I want to apply conditional formatting to a specific column of an ht: 
hytd <- set_text_color(hytd, 2:9, 4:5, where(hytd > 0), 'green')).
If I subset this column to another ht-object I can do this, but then I struggle to bind all again and not lose formatting.
I would like also to make it through if then else ( if it is > 0 then 'green' else 'red'), but it seems to be not feasible.

Thanks

**Comment by hughjonesd** [comment]
Hi Daria

Try something like:

    where(col(hytd) %in% 4:5 & row(hytd) %in% 2:9 & hytd > 0)

Cheers,
David
