### ISSUE TITLE
Feature request: incorporate tidyselect helpers

### ISSUE THREAD

**Issue by harrismcgehee** [hughjonesd/huxtable#42]
First, great package. 

Have you thought about including an easier way to specify columns rather than strictly integers, perhaps by incorporating the [dplyr select helpers](https://www.rdocumentation.org/packages/dplyr/versions/0.7.3/topics/select_helpers)/[`tidyselect` package](https://cran.r-project.org/web/packages/tidyselect/index.html)?

The use case would be something like this:
Instead of breaking your pipe to find the column positions:
```
df <- hux(
        Employee     = c('John Smith', 'Jane Doe', 'David Hugh-Jones'), 
        Salary       = c(50000, 50000, 40000),
        Age          = c(50, 50, 40),
        add_colnames = TRUE
      )                               

boldcols <- stringr::str_subset(names(df),"a")
bordercols <- stringr::str_subset(names(df),"[Aa]")

df %>% 
      set_bold(1, boldcols, TRUE)          %>% 
      set_bottom_border(1, bordercols, 1)
```
you could use the select helpers:
```
hux(
        Employee     = c('John Smith', 'Jane Doe', 'David Hugh-Jones'), 
        Salary       = c(50000, 50000, 40000),
        Age          = c(50, 50, 40),
        add_colnames = TRUE
      )                               %>% 
      set_bold(1, contains("a"), TRUE)          %>% 
      set_bottom_border(1, matches("[Aa]"), 1)
```

**Comment by hughjonesd** [comment]
Interesting idea. I'll see if it is doable. Or, if you want to contribute a
pull request, go ahead.

-- 
Sent from Gmail Mobile

**Comment by hughjonesd** [comment]
Well, that was easier than I thought. Please test. Note that this only works in columns, not rows, and you still need to specify the row - e.g.

      set_bottom_border(1, everywhere, matches("[Aa]"), 1)

Probably the whole row/column specification thing needs a rethink, it is pretty complex by now.

**Comment by hughjonesd** [comment]
Hey, did this work for you?
