### ISSUE TITLE
Automatically break wide tables

### ISSUE THREAD

**Issue by kusmi** [hughjonesd/huxtable#46]
If I have a wide table, it just overflows the paper on latex output. E.g.:

[Example.pdf](https://github.com/hughjonesd/huxtable/files/1748646/Example.pdf)

```{r}
library(huxtable)
ht <- hux(
        Huxtable = c('John Smith', 'Jane Doe', 'David Hugh-Jones'),
        Salary = c(50000, 50000, 40000),
        Salary2 = c(50000, 50000, 40000),
        Salary3 = c(50000, 50000, 40000),
        Salary4 = c(50000, 50000, 40000),
        Salary5 = c(50000, 50000, 40000),
        Salary6 = c(50000, 50000, 40000),
        Salary7 = c(50000, 50000, 40000),
        Salary8 = c(50000, 50000, 40000),
        add_colnames = TRUE
      )

bold(ht)[1,]           <- TRUE
bottom_border(ht)[1,]  <- 1
align(ht)[,2]          <- 'right'
right_padding(ht)      <- 10
left_padding(ht)       <- 10
#width(ht)              <- 0.35
number_format(ht)      <- 0

ht
```

so it would be nice, if huxtable would support that as well. The only other table package which supports breaking wide tables seems to be pander.

**Comment by hughjonesd** [comment]
I understand the issue, but I don't know how to automatically decide if a
table will overrun or not from within LaTeX itself - let alone
programmatically from within R. Suggestions welcome!

**Comment by hughjonesd** [comment]
I just wondered if you realised you can do

```
ht1 <- ht[, 1:5]
ht2 <- ht[, c(1, 6:9)]
```

and break the files yourself.

**Comment by hughjonesd** [comment]
Closing. Feel free to reopen if you have suggestions.
