### ISSUE TITLE
as_Workbook: must have at least 2 columns or 1 and add_rownames = TRUE

### ISSUE THREAD

**Issue by md0u80c9** [hughjonesd/huxtable#53]
Hi,

I called as_Workbook on a data frame which was 1 column by 6 rows. This caused the following error:

Error in apply(numbers, 2, all) : dim(X) must have a positive length.

I suspect that is because it is expecting at least two columns of data. When there is 1 column, adding add_rownames = TRUE fixes it.

However, I suspect it's entirely reasonable for a table to sometimes consist of one column and not wish to export row names (perhaps because you're doing post-processing on it).

Does that apply line need to have a bounds check so it is only applied if the total columns is >= 2?

**Comment by hughjonesd** [comment]
Try now with github master.

**Comment by md0u80c9** [comment]
Fab - that looks to be working :-).
