### ISSUE TITLE
as_Workbook with several sheets

### ISSUE THREAD

**Issue by pgtpg** [hughjonesd/huxtable#54]
Hello,

I would like to know if it's possible to save a huxtable to a sheet of a workbook ? I thought as_Workbook command did that, but it seems to be able just to save a huxtable to a workbook with a unique sheet. I have a lot of huxtables to export to one excel file with several sheets, I wondered if it's possible.

Thank you !

**Comment by hughjonesd** [comment]
Please read the documentation for `?as_Workbook`, in particular the `Workbook` and `sheet` arguments. If these don't work for you, please open a new issue describing the error.

**Comment by pgtpg** [comment]
My bad, I misread the documentation... Sorry !
