### ISSUE TITLE
Stop scientific notation printing when numeric values >= 1000

### ISSUE THREAD

**Issue by RickPack** [hughjonesd/huxtable#55]
I have not found a solution for scientific notation printing when numeric values >= 1000
```
options(scipen=999, digits = 8)
a <- data.frame (b = 1000)
a_hux <- as_hux(a, add_colnames = TRUE)

> a_hux
  b                          
  1e+3   
```

**Comment by RickPack** [comment]
Maybe this is user error but I show that while the number_format argument does not prevent scientific notation printing, the number_format function works on my machine.
```
a <- as_hux(c(1.2121, 1010), number_format = "%1.3f")
> a
  1.23                       
  1.23e+03  

number_format(a)[2,] <- "%1.0f"
> a
  1.23                       
  1234 
```

**Comment by hughjonesd** [comment]
?number_format
-- 
Sent from Gmail Mobile

**Comment by hughjonesd** [comment]
Unsurprising, since there is no number_format argument to as_hux.

**Comment by RickPack** [comment]
Good grief. My mistake and thank you.
