### ISSUE TITLE
pdf issues

### ISSUE THREAD

**Issue by helophilus** [hughjonesd/huxtable#6]
Hi. Thanks for the package. I have one or two issues attempting to make a pdf document using R markdown.

I find with wider tables, they are not positioned centrally despite being 'told to'. And the thickness of border lines isn't affected by the value .

---
title: "Example"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(huxtable)
options(huxtable.print=print_latex)
```

### Example

Example of a table.

But i) isn't positioned in the centre of the page and, ii) horizontal borders are all reproduced with the same thickness.

```{r table}
ht <- hux(
Employee = c('John Smith', 'Jane Doe', 'David Hugh-Jones'),
Salary = c(50000, 50000, 40000),
Age = c(42, 57, 29),
Sex = c('Male','Female','Male'),
HouseNo = c(132,87,56),
Present = c("Yes","Yes","No"),
add_colnames = TRUE
)
position(ht) = "center"
top_border(ht)[1,]=5
bottom_border(ht)[1,]=1
bottom_border(ht)[4,]=3
ht
```

Are these just r markdown issues that I have to live with, or might there be a fix?
Thanks.

**Comment by hughjonesd** [comment]
The thickness issue you have to live with (see the "design principles"
vignette; I'll mention this in the docs for ?xxx_border). The position
issue is more subtle. One issue is that your table is wider than the
default of 0.5. If you set width(ht) = 0.75, you get a more acceptable
outcome.

David

**Comment by helophilus** [comment]
Thanks for replying so quickly, and the tip for centering.

Colin
