### ISSUE TITLE
Support for quantreg

### ISSUE THREAD

**Issue by mattmoo** [hughjonesd/huxtable#61]
Great package! Is there any chance that support for `quantreg` is on the horizon?

**Comment by hughjonesd** [comment]
Talk to the 'broom' guys.
-- 
Sent from Gmail Mobile

**Comment by hughjonesd** [comment]
Actually afaics `broom` already has `quantreg` support. So, maybe you mean something else?

**Comment by hughjonesd** [comment]
WFM:
```
library(quantreg)
library(huxtable)
tmp <- rq(Petal.Width ~ Sepal.Length, data = iris)
huxreg(tmp, error_format = '{conf.low} / {conf.high}')
```

**Comment by mattmoo** [comment]
Thanks Hugh. That looks like almost what I want., but with no statistical testing.

It seems like in `quantreg` the stats are passed off to `boot.rq` (usually generated using `summary(args$x, se="boot")`)

I haven't been able to get `tidy` to generate p-values, although maybe that's `broom`'s issue, as you say.

**Comment by hughjonesd** [comment]
If summary generates P values then you could try writing a tidy method for
summary.quantreg. I think broom is in an awkward place where it can only
offer very minimal consistency guarantees. Perhaps  that is the inevitable
consequence of it being a facade over many different projects.
-- 
Sent from Gmail Mobile
