### ISSUE TITLE
Change "Unrecognized coefficient names" from Error to Warning?

### ISSUE THREAD

**Issue by mattmoo** [hughjonesd/huxtable#62]
It would be handy for generating a big list of names and applying them to all tables, unless there's a good reason for it not to be :)

**Comment by hughjonesd** [comment]
So the use case is you have many different tables generated with `huxreg`
and you want to use a single vector of coefficient names for all of them. I
understand the issue, but I wonder how common it is. The trade-off is that
someone who mistyped a coefficient name will get a warning, not an error,
and the warning may be buried in page 37 of the PDF.

I'd suggest a workaround like:

    my_huxreg <- function(models, coefs) {
      for (m in models) coefs <- intersect(coefs, names(coef(m))) #
`Reduce` would be more elegant
      huxreg(models, coefs  = coefs)
    }
