### ISSUE TITLE
colspan border when exporting to docx

### ISSUE THREAD

**Issue by raiphilibert** [hughjonesd/huxtable#69]
I used a colspan to merge some table headers. However, when exporting to word, the right border does not show up. 

Reproducible example (see output screenshot below):
```
library(huxtable)
library(flextable)


ht <- huxtable(mtcars[1:5,2:10])  %>% huxtable(add_colnames = TRUE) %>% set_all_borders(1)
colspan(ht)[2,1] <- 9
ht <- set_align(ht,2,1,'center')
ht <- set_bold(ht,2,1,TRUE)
ht <- ht %>% set_caption(sprintf('Mtcars example')) %>%
  set_font_size(nrow(ht),everywhere,7) %>% set_all_borders(1)

quick_docx(ht)
```

![image](https://user-images.githubusercontent.com/12389916/42105675-1cc500dc-7b86-11e8-9133-72a91ffc7b4f.png)

It would also be great if we could export the caption but I think that this is more of an issue with the flextable object than the huxtable.

**Comment by hughjonesd** [comment]
Thank you for the bug report. MWE:

```
ht <- huxtable(mtcars[1:5,2:10], add_colnames = TRUE)
colspan(ht)[2,1] <- 9
ht <- ht %>% set_all_borders(1)
quick_docx(ht)
```

Seems to be to do with how flextable represents borders.

**Comment by hughjonesd** [comment]
Could you check if current master fixes your problem (and doesn't cause any others)?

**Comment by raiphilibert** [comment]
Thanks! It's all fixed now (and no other problems that I can see).
