### ISSUE TITLE
output huxtable as worksheet / multiple huxtables as workbook

### ISSUE THREAD

**Issue by md0u80c9** [hughjonesd/huxtable#76]
Hi,

Using huxtable for quite a large project with Excel output. So far so good - and the flexibility for outputs is excellent!

One thing I've found is that I can export a single huxtable to a sheet. However I need to output nine huxtables to form a workbook.

Would there be a way to either create a worksheet object rather than a workbook; or to allow the input to be a named list of huxtables (where the names form the sheet names)? Currently my workaround is to glue them all together in openxlsx; but this results in making each table separately, making a new workbook, and then deleting the old ones, which is far from ideal.

**Comment by hughjonesd** [comment]
Sounds reasonable, I'll look into it.
-- 
Sent from Gmail Mobile

**Comment by hughjonesd** [comment]
Apologies if I'm missing something,  but doesn't the "sheet" argument to
as_Workbook do this for you?


-- 
Sent from Gmail Mobile
