### ISSUE TITLE
as_workbook: rename Workbook parameter as workbook

### ISSUE THREAD

**Issue by md0u80c9** [hughjonesd/huxtable#78]
Hi,

Not sure if there was a rationale for the capitalisation of the Workbook parameter in as_workbook.

However, it flags up if you use a style checker (I tend to use Jim Hester's lintr package to check my package code every now and then. It also seems discordant with other parameters in the package which are all lower case.

Appreciating it's a breaking change - would it be possible to get it to lower case for consistency (perhaps allow both cases as parameters but warn against the capitalised one)?

**Comment by hughjonesd** [comment]
Yup, but it fits the capitalisation of the openxlsx object. Closing.
-- 
Sent from Gmail Mobile
