### ISSUE TITLE
Table formatting on Word Documents

### ISSUE THREAD

**Issue by jestarr** [hughjonesd/huxtable#88]
I'm having an issue with formatting my tables on Word documents.  When I knit to HTML, they look just fine.  

When I knit to Word I get the following error.  
 `## Warning in knit_print.huxtable(x, ...): Unrecognized output format "docx". Using `to_screen` to print huxtables.`
`## Set options("huxtable.knitr_output_format") manually to "latex", "html", "rtf", "md" or "screen".
`

How would I set-up my R Markdown file to fix this issue to allow for knitting to PDF, HTML and Word properly?

**Comment by hughjonesd** [comment]
Unfortunately, huxtables can't print directly to Word, except via markdown which loses most of the formatting. See `?as_flextable` for more details. If you want to print via markdown you could do
something like:

```
if (guess_knitr_output_format() == "docx") options(huxtable.print = print_md)
```
in your setup chunk.

Leaving this open for now. I'm not sure how to handle docx. One option is to fall back to markdown but issue a warning.

**Comment by jestarr** [comment]
I tried doing that and got this error message.

`Error in guess_knitr_output_format() : 
  could not find function "guess_knitr_output_format"
Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval
Execution halted`

**Comment by hughjonesd** [comment]
That seems unlikely. `guess_knitr_output_format` goes back to huxtable 0.2.0. Maybe you haven't called `library(huxtable)` first? In any case, no offence, but this is for bug reports -- please, if you have questions, put them on stackoverflow or a similar place.
