### ISSUE TITLE
col_width not carried through latex rows

### ISSUE THREAD

**Issue by mikebader** [hughjonesd/huxtable#91]
Thank you for the package! It has been a huge help. 

I have been having trouble with the column width property when printing to PDF (`quick_pdf()`) or printing to a LaTeX string (`to_latex()`). The column widths are correct when the `tabularx` environment is defined; but, huxtable then uses `multirow` commands in the body of the text that are defined with simple `l` and `c` column-types. The result is that the final table does not keep the appropriate column widths. 

For example: 
```
library(huxtable)

N <- 1000
x1 <- rnorm(N, )
x2 <- rnorm(N, 3, .75)
x3 <- rnorm(N, .5, .1)
y <- rnorm(N, (1/3)*x1 + .5*x2 + 1*x3, .5)
df <- data.frame(y,x1,x2,x3)

m1 <- lm(y ~ x1, data=df)
m2 <- lm(y ~ x1 + x2, data=df)
m3 <- lm(y ~ x1 + x2 + x3, data=df)

ht <- huxreg(m1, m2, m3, statistics=c('nobs'))
print_latex(ht)
```
provides the output: 

```
\begin{table}[h]
\centering
    \providecommand{\huxb}[2][0,0,0]{\arrayrulecolor[RGB]{#1}\global\arrayrulewidth=#2pt}
    \providecommand{\huxvb}[2][0,0,0]{\color[RGB]{#1}\vrule width #2pt}
    \providecommand{\huxtpad}[1]{\rule{0pt}{\baselineskip+#1}}
    \providecommand{\huxbpad}[1]{\rule[-#1]{0pt}{#1}}
  \begin{tabularx}{1\textwidth}{p{0.5\textwidth} p{0.166\textwidth} p{0.166\textwidth} p{0.166\textwidth}} <-- CORRECT WIDTHS HERE

<snip>

\multicolumn{1}{!{\huxvb{0}}l!{\huxvb{0}}}{\huxtpad{4pt}\raggedright (Intercept)\huxbpad{4pt}} &
\multicolumn{1}{r!{\huxvb{0}}}{\huxtpad{4pt}\raggedleft 2.020 ***\huxbpad{4pt}} &
\multicolumn{1}{r!{\huxvb{0}}}{\huxtpad{4pt}\raggedleft 0.550 ***\huxbpad{4pt}} &
\multicolumn{1}{r!{\huxvb{0}}}{\huxtpad{4pt}\raggedleft 0.103~~~~\huxbpad{4pt}} \tabularnewline[-0.5pt] <-- LAST THREE COLUMNS DEFINED AS r ENVIRONMENT HERE
```
The same formatting appears if I use the `quick_pdf()` command as well.

**Comment by hughjonesd** [comment]
Yup. Width is a bit broken at the moment. I think the ultimate solution is to move to the tabu package. The problem is that if I replace the l/c/r multicols with p-style multicols, then that automatically imposes wrapping.

So, for your purposes, you might try setting `wrap(ht) <- TRUE`?

**Comment by mikebader** [comment]
That makes sense, thank you! I used `wrap(ht) <- TRUE` but the padding increased so there is space between cells. Is there a way to wrap and eliminate the padding in LaTeX?

**Comment by hughjonesd** [comment]
Maybe... the whole thing needs a rework... does `set_all_padding` not help?

**Comment by mikebader** [comment]
I tried `set_all_padding` before and after setting `wrap(ht) <- TRUE` keeps space between rows. It's possible that it is the extra spaces from the cell wrapping so I can experiment with the widths. I'm 95% of the way there with huxtable, though -- so thank you so much!

**Comment by mikebader** [comment]
The extra space is still present regardless of whether I put `set_all_padding` before or after I set `wrap(ht) <- TRUE`. I think that it might be the non-breaking spaces wrapping inside the cell. I can play with it to see if I can get it to work. huxtable got me 95% of the way there, so thank you!

**Comment by hughjonesd** [comment]
Hi Mike, if you could try latest github and see if things are improved at all, that would be very useful.
