### ISSUE TITLE
set_wrap() fails with latex markdown

### ISSUE THREAD

**Issue by nstets** [hughjonesd/huxtable#92]
I am trying to use huxtable for a pdf report. My issue is with `set_wrap()` and` wrap()`. When I use the console to print the huxtable, the wrap works, but when I knit to markdown the PDF doesn't have the table at all, though there isn't an error.

When I tried to recreate this issue, it actually worked, but it's not working with my report, so I am stumped. In this example I have a data frame y with all strings.  (Neither `set_wrap()` or` wrap() <- T` creates an table in the PDF, though both output to the console the way I'd like). 

```
ht <- as_hux(y) %>%
  set_width(c(.8)) %>%
  set_bold(col = 1:2, row = seq(1,len, by = 7), T) #%>%
  # set_wrap(col = 2, 
  #          # people involved row
  #          #row = seq(1,len, by = 7) + 3, 
  #          row = 5, 
  #          T)

wrap(ht) <- T

```

`r ht`
```

**Comment by hughjonesd** [comment]
Sounds like a nasty bug. Could you run Rmarkdown with keep_tex: true in the header and see what tex is being produced?

**Comment by hughjonesd** [comment]
Hi, did you solve your problem?
