### ISSUE TITLE
Ability to use resizebox in LaTeX

### ISSUE THREAD

**Issue by nikolassch** [hughjonesd/huxtable#96]
Hi, I am trying to printa table to PDF. The issue is that it is too large, so I would like to resize the whole table to fit the page (so implicitly reducing the font size) such as would be done in latex by resizebox or similar. 
The set_width() command unfortunately does not do the job. Instead, it seems when I choose smaller values, it shifts the table further to the right.
I can decrease the font-size manually but this is a bit tedious. 
Also the set_position("center") does not truely work (in the sense that it never exceeds the left boundary).
Could you create an environment that fixes this? 

Large table seem a common issue in my experience.

Thanks a lot in advance

**Comment by hughjonesd** [comment]
Can you provide a MWE? Thanks

**Comment by nikolassch** [comment]
---
title: "MWE_oversized_table"
author: "Niko"
date: "December 17, 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r cars}
library(huxtable)
library(tidyverse)
lm1 <- lm(data = cars, formula = dist ~ speed)
huxreg(lm1, lm1, lm1, lm1, lm1, lm1, lm1, lm1) %>%
  set_position("left")
```

Trying to adjust size: --> does not work

```{r}
huxreg(lm1, lm1, lm1, lm1, lm1, lm1, lm1, lm1) %>%
  set_width(.5) %>%
  set_position("left") 
```

Trying to center so excess is on both sides equally. --> also does not work

```{r}
huxreg(lm1, lm1, lm1, lm1, lm1, lm1, lm1, lm1) %>%
  set_width(.5) %>%
  set_position("center")
```

This works but is tideous:

```{r}
huxreg(lm1, lm1, lm1, lm1, lm1, lm1, lm1, lm1) %>%
  set_font_size(5) %>%
  set_position("left")
```

**Comment by nikolassch** [comment]
[mwe.txt](https://github.com/hughjonesd/huxtable/files/2687498/mwe.txt)

**Comment by hughjonesd** [comment]
I think this is probably fixed now that `set_position("center")` works. In particular, using `width` of `0.75` and center looks pretty OK to me. Reopen if you disagree.
