### ISSUE TITLE
Can't install latex dependencies

### ISSUE THREAD

**Issue by christianlindell** [hughjonesd/huxtable#97]
**Describe the bug**
When I run huxtable::install_latex_dependencies(), it can't find som of the latex packages. I get the following output:

> library(tinytex)
> huxtable::install_latex_dependencies()
Trying to install packages: caption, siunitx, xcolor, multirow, hhline, tabularx, threeparttable
If this fails, try running the following on the command line (you may need admin permissions):
  tlmgr install caption siunitx xcolor multirow hhline tabularx threeparttable
tlmgr install caption siunitx xcolor multirow hhline tabularx threeparttable
tlmgr.pl install: package hhline not present in repository.
tlmgr.pl install: package tabularx not present in repository.
tlmgr.pl: action install returned an error; continuing.
tlmgr.pl: package repository http://ftp.acc.umu.se/mirror/CTAN/systems/texlive/tlnet (verified)
tlmgr.pl install: package already present: caption
tlmgr.pl install: package already present: multirow
tlmgr.pl install: package already present: siunitx
tlmgr.pl install: package already present: threeparttable
tlmgr.pl install: package already present: xcolor
tlmgr.pl: An error has occurred. See above messages. Exiting.
[1] TRUE

**System details**
Windows 10, R 3.4.4, Huxtable 4.3.0. Latest version of tinytex (installed 2018-12-17).

**Comment by hughjonesd** [comment]
Sorry for the delay. Did you try tlmgr manually using the suggested command? What happened?

**Comment by zilch42** [comment]
Hi, I'm having the same issue with hhline and tabularx. I have tried running the suggested command in terminal with no success. 

hhline.sty and tabular.sty are both in /Users/MYNAME/Library/TinyTeX/texmf-dist/tex/latex/tools/ which I think is where they should be? Is it a case of tlmgr just not knowing they're there (or that they're part of 'tools' rather than being their own packages)?

**Comment by hughjonesd** [comment]
Can you post output both from within R and from the command line?

**Comment by hughjonesd** [comment]
Also report which CTAN repository you are using, if poss

**Comment by zilch42** [comment]
install_latex_dependencies() outputs over 1000 lines but here are the last ones that seem relevant:

tlmgr install caption siunitx xcolor multirow hhline tabularx threeparttable
tlmgr install: package hhline not present in repository.
tlmgr install: package tabularx not present in repository.
tlmgr: action install returned an error; continuing.
tlmgr: package repository http://mirror.aarnet.edu.au/pub/CTAN/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr install: package already present: caption
tlmgr install: package already present: multirow
tlmgr install: package already present: siunitx
tlmgr install: package already present: threeparttable
tlmgr install: package already present: xcolor
tlmgr: An error has occurred. See above messages. Exiting.
tlmgr path add
[1] FALSE

Terminal command and output:

Golden-Lappy:zilch$ tlmgr install caption siunitx xcolor multirow hhline tabularx threeparttable
tlmgr: package repository http://mirror.aarnet.edu.au/pub/CTAN/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr install: package already present: caption
tlmgr install: package hhline not present in repository.
tlmgr install: package already present: multirow
tlmgr install: package already present: siunitx
tlmgr install: package tabularx not present in repository.
tlmgr install: package already present: threeparttable
tlmgr install: package already present: xcolor
tlmgr: action install returned an error; continuing.
tlmgr: An error has occurred. See above messages. Exiting.

I assume the CTAN repo is http://mirror.aarnet.edu.au/pub/CTAN/systems/texlive/tlnet

**Comment by hughjonesd** [comment]
Could you try a different mirror?
-- 
Sent from Gmail Mobile

**Comment by zilch42** [comment]
Thanks, I've just tried a couple, same result.

`Golden-Lappy:zilch$ tlmgr -repository http://ctan.math.illinois.edu/systems/texlive/tlnet install hhline tabularx
tlmgr: package repository http://ctan.math.illinois.edu/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr install: package hhline not present in repository.
tlmgr install: package tabularx not present in repository.
tlmgr: action install returned an error; continuing.
tlmgr: An error has occurred. See above messages. Exiting.

Golden-Lappy:zilch$ tlmgr -repository http://mirrors.rit.edu/CTAN/systems/texlive/tlnet install hhline tabularx
tlmgr: package repository http://mirrors.rit.edu/CTAN/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr install: package hhline not present in repository.
tlmgr install: package tabularx not present in repository.
tlmgr: action install returned an error; continuing.
tlmgr: An error has occurred. See above messages. Exiting.

Golden-Lappy:zilch$ tlmgr option repository http://mirrors.rit.edu/CTAN/systems/texlive/tlnet
tlmgr: setting default package repository to http://mirrors.rit.edu/CTAN/systems/texlive/tlnet

Golden-Lappy:zilch$ tlmgr install hhline tabularx
tlmgr: package repository http://mirrors.rit.edu/CTAN/systems/texlive/tlnet (not verified: gpg unavailable)
tlmgr install: package hhline not present in repository.
tlmgr install: package tabularx not present in repository.
tlmgr: action install returned an error; continuing.
tlmgr: An error has occurred. See above messages. Exiting.`

**Comment by hughjonesd** [comment]
OK, should be fixed in master shortly.
