### ISSUE TITLE
background image for a cell

### ISSUE THREAD

**Issue by edwardlobo** [hughjonesd/huxtable#99]
I am looking to show a diagonal line in a cell with 2 values. 
From what I understand I'll have to  use 2 columns.
In the first column, I'll top and left align and in the second column I'll right and bottom align
Then if I put a background image of a diagonal line I should have the appearance of a single cell separated by a diagonal line with one value on top of the diagonal line and another on the bottom of the diagonal line.

**Comment by hughjonesd** [comment]
Is this a request for an enhancement to huxtable? If so, what exactly do you want?

**Comment by edwardlobo** [comment]
Sorry it is for enhancement
Please see this site: https://tex.stackexchange.com/questions/27193/latex-table-cell-with-a-diagonal-line-and-2-sub-cells
Is there a way to do Date/Room for the entire column not just the header ?
Thanks for looking into this

**Comment by hughjonesd** [comment]
Please could you state clearly the enhancement that you want in huxtable.
If you could use the template that I provided for you, that would be
helpful. If you can’t do this, I’m going to close this issue.
-- 
Sent from Gmail Mobile

**Comment by hughjonesd** [comment]
Closing. Feel free to reopen if you can clearly state what you want.
